Repository DestinyItemManager/DIM, pull requests merged in 2019-05, with the labels that each got.

#3800 Revelry missing items
  src/data/d2-events.json
Labels: Enhancement, Feature: Search

#3803 murmuration is season 4
  src/data/d2-seasons.json
Labels: Bug, Feature: Search

#3841 Loadout Optimizer: Perk multi select
  docs/CHANGELOG.md
  src/app/d2-loadout-builder/LockArmorAndPerks.tsx
  src/app/d2-loadout-builder/PerkPicker.m.scss
  src/app/d2-loadout-builder/PerkPicker.m.scss.d.ts
  src/app/d2-loadout-builder/PerkPicker.tsx
  src/app/d2-loadout-builder/PerksForBucket.tsx
  src/app/d2-loadout-builder/generated-sets/GeneratedSetItem.m.scss
  src/app/d2-loadout-builder/generated-sets/GeneratedSets.tsx
  src/app/d2-loadout-builder/generated-sets/utils.ts
  src/app/d2-loadout-builder/locked-armor/SelectableBungieImage.m.scss
  src/app/d2-loadout-builder/locked-armor/SelectableBungieImage.tsx
  src/app/dim-ui/Sheet.scss
  src/app/dim-ui/Sheet.tsx
  src/app/dim-ui/common.m.scss
  src/app/item-picker/ItemPicker.scss
  src/locale/dim.json
Labels: Feature: Loadout Optimizer

#3847 Let season of opulence commence
  src/data/d2-seasons.json
Labels: Feature: Search
