Repository DestinyItemManager/DIM, pull requests merged in 2021-11, with the labels that each got.

#7184 Replace many usages of "primStat" with "power", renames
  .vscode/settings.json
  src/app/compare/Compare.tsx
  src/app/destiny1/loadout-builder/D1LoadoutBuilder.tsx
  src/app/destiny1/loadout-builder/utils.ts
  src/app/farming/actions.ts
  src/app/gear-power/GearPower.m.scss
  src/app/gear-power/GearPower.m.scss.d.ts
  src/app/gear-power/GearPower.tsx
  src/app/infuse/InfusionFinder.tsx
  src/app/inventory/BadgeInfo.tsx
  src/app/inventory/InventoryItem.tsx
  src/app/inventory/ItemPowerSet.tsx
  src/app/inventory/item-move-service.ts
  src/app/inventory/item-types.ts
  src/app/inventory/spreadsheets.ts
  src/app/inventory/store/d1-item-factory.ts
  src/app/inventory/store/d2-item-factory.ts
  src/app/inventory/stores-helpers.ts
  src/app/item-popup/ItemPopupHeader.tsx
  src/app/loadout-builder/generated-sets/CompareDrawer.tsx
  src/app/loadout-builder/process-worker/types.ts
  src/app/loadout-builder/process/mappers.ts
  src/app/loadout-builder/utils.ts
  src/app/loadout-drawer/auto-loadouts.ts
  src/app/loadout-drawer/loadout-utils.ts
  src/app/loadout-drawer/postmaster.ts
  src/app/organizer/Columns.tsx
  src/app/progress/milestone-items.ts
  src/app/search/d1-known-values.ts
  src/app/search/d2-known-values.ts
  src/app/search/search-filters/dupes.tsx
  src/app/search/search-filters/known-values.tsx
  src/app/search/search-filters/range-overload.tsx
  src/app/search/search-filters/stats.tsx
  src/app/settings/SettingsPage.tsx
  src/app/shell/filters.ts
  src/app/utils/comparators.ts
Labels: no changelog

#7223 Upgrades
  package.json
  yarn.lock
Labels: no changelog

#7222 Prevent Chrome from using auto-dark-mode
  src/index.html
Labels: no changelog

#7224 Maybe get the right content type for source maps
  src/htaccess
Labels: no changelog

#7185 Make loadout sheets open at equal heights.
  src/app/dim-ui/Sheet.tsx
  src/app/loadout-drawer/LoadoutDrawer.tsx
  src/app/loadout-drawer/LoadoutDrawerOptions.tsx
  src/app/loadout/ModPicker.tsx
  src/app/loadout/mod-assignment-drawer/ModAssignmentDrawer.tsx
  src/app/loadout/plug-drawer/PlugDrawer.tsx
Labels: no changelog

#7228 Fix clearing space from loadouts
  src/app/loadout-drawer/loadout-apply.ts
Labels: no changelog

#7226 Fix mods wrapping in plug drawer selections.
  src/app/loadout/plug-drawer/Footer.m.scss
Labels: no changelog

#7229 Show a corrected number of items in the loadout apply notification
  config/i18n.json
  src/app/inventory/MoveNotifications.tsx
  src/app/loadout-drawer/loadout-apply.ts
  src/locale/dim.json
Labels: no changelog

#7236 Only filter loadouts to matching class sometimes
  src/app/destiny1/loadout-builder/GeneratedSet.tsx
  src/app/item-actions/ItemActionsDropdown.tsx
  src/app/loadout-builder/generated-sets/GeneratedSetButtons.tsx
  src/app/loadout-drawer/LoadoutPopup.tsx
  src/app/loadout-drawer/MaxlightButton.tsx
  src/app/loadout-drawer/loadout-apply.ts
  src/app/organizer/ItemTable.tsx
Labels: no changelog

#7230 Stop showing mod placements in LO while processing.
  src/app/loadout-builder/LoadoutBuilder.tsx
Labels: no changelog

#7231 Disable Optimizer during maintenance.
  config/i18n.json
  src/app/loadout-builder/LoadoutBuilder.m.scss
  src/app/loadout-builder/LoadoutBuilder.m.scss.d.ts
  src/app/loadout-builder/LoadoutBuilder.tsx
  src/app/loadout-builder/process/useProcess.ts
  src/locale/dim.json
Labels: no changelog

#7232 Remove enable parameter from CloseableContainer.
  src/app/dim-ui/ClosableContainer.tsx
  src/app/loadout/plug-drawer/SelectablePlug.tsx
Labels: no changelog

#7240 simplify energy overlay svgs
  src/app/inventory/ItemIcon.tsx
Labels: no changelog

#7244 Upgrade framer motion
  package.json
  src/app/search/SearchBar.tsx
  yarn.lock
Labels: no changelog

#7248 CSS modules for notifications
  src/app/notifications/Notification.m.scss
  src/app/notifications/Notification.m.scss.d.ts
  src/app/notifications/Notification.scss
  src/app/notifications/Notification.tsx
  src/app/notifications/NotificationsContainer.m.scss
  src/app/notifications/NotificationsContainer.m.scss.d.ts
  src/app/notifications/NotificationsContainer.tsx
Labels: no changelog

#7254 Replace DnD HOCs with hooks
  src/app/destiny1/loadout-builder/ExcludeItemsDropTarget.tsx
  src/app/destiny1/loadout-builder/LoadoutBuilderDropTarget.tsx
  src/app/destiny1/loadout-builder/loadout-builder.scss
  src/app/dim-api/actions.ts
  src/app/dim-ui/ActivityTracker.tsx
  src/app/farming/actions.ts
  src/app/inventory/DraggableInventoryItem.tsx
  src/app/inventory/StoreBucket.scss
  src/app/inventory/StoreBucket.tsx
  src/app/inventory/StoreBucketDropTarget.m.scss
  src/app/inventory/StoreBucketDropTarget.m.scss.d.ts
  src/app/inventory/StoreBucketDropTarget.tsx
  src/app/inventory/StoreInventoryItem.tsx
  src/app/inventory/drag-events.ts
  src/app/inventory/store/hooks.ts
  src/app/loadout-builder/LoadoutBucketDropTarget.m.scss
  src/app/loadout-builder/LoadoutBucketDropTarget.m.scss.d.ts
  src/app/loadout-builder/LoadoutBucketDropTarget.tsx
  src/app/loadout-builder/filter/LockArmorAndPerks.m.scss
  src/app/loadout-builder/filter/LockArmorAndPerks.tsx
  src/app/loadout-drawer/LoadoutDrawer.tsx
  src/app/loadout-drawer/LoadoutDrawerDropTarget.m.scss
  src/app/loadout-drawer/LoadoutDrawerDropTarget.m.scss.d.ts
  src/app/loadout-drawer/LoadoutDrawerDropTarget.tsx
  src/app/loadout-drawer/loadout-drawer.scss
  src/app/shell/Header.tsx
  src/app/shell/RefreshButton.tsx
  src/app/shell/refresh-events.ts
  src/app/vendors/SingleVendor.tsx
  src/app/vendors/Vendors.tsx
Labels: no changelog

#7249 Refactor developer page to hooks
  src/app/developer/Developer.tsx
Labels: no changelog

#7243 Loadouts page
  config/i18n.json
  config/webpack.js
  src/app/inventory/selectors.ts
  src/app/loadout-drawer/GeneratedLoadoutStats.tsx
  src/app/loadout-drawer/LoadoutDrawer.tsx
  src/app/loadout-drawer/LoadoutPopup.tsx
  src/app/loadout-drawer/auto-loadouts.ts
  src/app/loadout-drawer/loadout-types.ts
  src/app/loadout-drawer/selectors.ts
  src/app/loadout/Loadouts.m.scss
  src/app/loadout/Loadouts.m.scss.d.ts
  src/app/loadout/Loadouts.tsx
  src/app/shell/Destiny.tsx
  src/app/shell/Header.tsx
  src/app/shell/icons/Library.ts
  src/global.d.ts
  src/locale/dim.json
  yarn.lock
Labels: no changelog

#7251 Router 5.1
  .gitignore
  .vscode/settings.json
  src/app/App.tsx
  src/app/shell/Destiny.tsx
  yarn.lock
Labels: no changelog

#7252 Refactor loadout drawer a bit
  src/app/destiny1/loadout-builder/GeneratedSet.tsx
  src/app/item-actions/ActionButtons.tsx
  src/app/item-triage/ItemTriage.tsx
  src/app/loadout-builder/LoadoutBuilder.tsx
  src/app/loadout-builder/generated-sets/GeneratedSet.tsx
  src/app/loadout-drawer/LoadoutDrawer.tsx
  src/app/loadout-drawer/LoadoutDrawerBucket.tsx
  src/app/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/loadout-drawer/LoadoutDrawerOptions.tsx
  src/app/loadout-drawer/LoadoutPopup.tsx
  src/app/loadout-drawer/loadout-drawer-reducer.ts
  src/app/loadout-drawer/loadout-events.ts
  src/app/loadout/Loadouts.tsx
Labels: no changelog

#7253 useSelector instead of connect in a few places
  src/app/App.tsx
  src/app/compare/Compare.tsx
  src/app/destiny1/loadout-builder/D1LoadoutBuilder.tsx
  src/app/destiny1/record-books/RecordBooks.tsx
  src/app/destiny1/vendors/D1Vendor.tsx
  src/app/destiny1/vendors/D1VendorItems.tsx
  src/app/destiny1/vendors/D1Vendors.tsx
  src/app/dim-api/selectors.ts
  src/app/dim-ui/CollapsibleTitle.tsx
  src/app/dim-ui/ShowPageLoading.tsx
  src/app/farming/Farming.tsx
  src/app/farming/actions.ts
  src/app/farming/selectors.ts
  src/app/infuse/InfusionFinder.tsx
  src/app/inventory/ConnectedInventoryItem.tsx
  src/app/inventory/Stores.tsx
  src/app/inventory/selectors.ts
  src/app/inventory/spreadsheets.ts
  src/app/organizer/ItemTable.tsx
  src/app/progress/Pursuit.tsx
  src/app/records/PresentationNode.tsx
  src/app/records/PresentationNodeSearchResults.tsx
  src/app/records/Records.tsx
  src/app/search/SearchFilter.tsx
  src/app/settings/SettingsPage.tsx
  src/app/settings/Spreadsheets.tsx
  src/app/settings/WishListSettings.tsx
  src/app/shell/DefaultAccount.tsx
  src/app/shell/Destiny.tsx
  src/app/storage/DimApiSettings.tsx
  src/app/vendors/SingleVendor.tsx
  src/app/vendors/Vendors.tsx
Labels: no changelog

#7257 Clean out settings page a bit
  config/i18n.json
  src/app/accounts/selectors.ts
  src/app/settings/SettingsPage.tsx
  src/locale/dim.json
Labels: no changelog

#7250 Activity tracker refactor to hooks
  src/app/dim-ui/ActivityTracker.tsx
  src/app/shell/selectors.ts
Labels: no changelog

#7259 Remove warning for pre-Beyond-Light triumphs
  config/i18n.json
  src/app/records/PresentationNode.scss
  src/app/records/Record.m.scss
  src/app/records/Record.m.scss.d.ts
  src/app/records/Record.tsx
  src/locale/dim.json
Labels: no changelog

#7268 Fix for selectable plug on close click.
  src/app/loadout/plug-drawer/SelectablePlug.tsx
Labels: no changelog

#7273 Disable LO when all items missing sockets.
  src/app/loadout-builder/LoadoutBuilder.tsx
Labels: no changelog

#7269 Remove plug stats from selectable plug.
  src/app/loadout/plug-drawer/SelectablePlug.m.scss
  src/app/loadout/plug-drawer/SelectablePlug.m.scss.d.ts
  src/app/loadout/plug-drawer/SelectablePlug.tsx
Labels: no changelog

#7279 Fix energy swap display in LO
  src/app/loadout-builder/generated-sets/GeneratedSetItem.tsx
Labels: no changelog

#7283 Fix async process race condition that led to deleted tags
  docs/CHANGELOG.md
  src/app/destiny1/vendors/vendor.service.ts
  src/app/inventory/StoreBucket.tsx
  src/app/inventory/actions.ts
  src/app/inventory/advanced-write-actions.ts
  src/app/inventory/d1-stores.ts
  src/app/inventory/d2-stores.ts
  src/app/inventory/dim-item-info.ts
  src/app/inventory/selectors.ts
  src/app/inventory/store/d1-item-factory.ts
  src/testing/test-utils.ts
Labels: Infrastructure: Sync

#7289 Add a useSetting hook that simplifies using settings
  src/app/compare/Compare.tsx
  src/app/destiny1/record-books/RecordBooks.tsx
  src/app/dim-ui/CustomStatTotal.tsx
  src/app/farming/Farming.tsx
  src/app/infuse/InfusionFinder.tsx
  src/app/item-popup/DesktopItemActions.tsx
  src/app/item-popup/ItemSocketsWeapons.tsx
  src/app/item-triage/ItemTriage.tsx
  src/app/records/Records.tsx
  src/app/settings/hooks.ts
Labels: no changelog

#7287 React Router v6 upgrade
  package.json
  src/app/App.tsx
  src/app/armory/ArmoryPage.tsx
  src/app/compare/selectors.ts
  src/app/item-popup/ItemDetails.tsx
  src/app/loadout-builder/LoadoutBuilderContainer.tsx
  src/app/loadout-drawer/LoadoutDrawerOptions.tsx
  src/app/loadout/Loadouts.tsx
  src/app/organizer/Organizer.tsx
  src/app/records/Records.tsx
  src/app/shell/AccountRedirectRoute.tsx
  src/app/shell/DefaultAccount.tsx
  src/app/shell/Destiny.tsx
  src/app/shell/Header.tsx
  src/app/vendors/SingleVendor.tsx
  src/app/vendors/VendorItemComponent.tsx
  src/app/vendors/VendorItems.tsx
  src/app/whats-new/WhatsNewLink.tsx
  yarn.lock
Labels: no changelog

#7292 Xur fixed in API, #6514 no longer required.
  package.json
  src/app/search/d2-known-values.ts
  src/app/vendors/Vendors.tsx
  yarn.lock
Labels: no changelog

#7295 Cleanup stuff from the stat mods PR
  src/app/dim-api/reducer.ts
  src/app/loadout-builder/generated-sets/GeneratedSet.tsx
  src/app/loadout-builder/mod-assignments.ts
  src/app/loadout-builder/process-worker/process.ts
  src/app/loadout-builder/process-worker/set-tracker.ts
  src/app/loadout-builder/process/useProcess.ts
  src/app/loadout-builder/types.ts
  src/app/loadout-drawer/loadout-types.ts
  src/app/loadout-drawer/loadout-utils.ts
  src/app/loadout-drawer/selectors.ts
Labels: no changelog

#7299 The Great Spelling Hunt
  .vscode/settings.json
  config/i18n.json
  docs/CHANGELOG.md
  docs/TRANSLATIONS.md
  src/app/dim-api/basic-actions.ts
  src/app/dim-ui/ClickOutside.tsx
  src/app/dim-ui/ClickOutsideRoot.tsx
  src/app/dim-ui/rich-destiny-text.ts
  src/app/inventory/item-move-service.ts
  src/app/inventory/item-types.ts
  src/app/inventory/move-item.ts
  src/app/item-popup/NotesArea.tsx
  src/app/item-popup/item-popup-actions.ts
  src/app/item-triage/ItemTriage.tsx
  src/app/loadout-builder/process/useProcess.ts
  src/app/loadout-drawer/LoadoutDrawer.tsx
  src/app/loadout-drawer/LoadoutDrawerOptions.tsx
  src/app/loadout-drawer/SavedModCategory.tsx
  src/app/loadout/ModPicker.tsx
  src/app/manifest/d1-manifest-service.ts
  src/app/manifest/manifest-service-json.ts
  src/app/search/d2-known-values.ts
  src/app/search/search-filters/dupes.tsx
  src/app/shell/refresh-events.ts
  src/app/wishlists/wishlist-file.ts
  src/locale/dim.json
  src/service-worker.ts
Labels: no changelog

#7276 LO README
  src/app/loadout-builder/README.md
Labels: no changelog

#7278 Better Plug Definition Display
  src/app/item-popup/ItemPerksList.tsx
  src/app/item-popup/Plug.tsx
  src/app/item-popup/PlugTooltip.tsx
  src/app/item-triage/ItemTriage.tsx
  src/app/loadout-builder/filter/LockArmorAndPerks.tsx
  src/app/loadout-drawer/SavedModCategory.tsx
  src/app/loadout/loadout-ui/LockedModIcon.tsx
  src/app/loadout/loadout-ui/PlugDef.m.scss
  src/app/loadout/loadout-ui/PlugDef.m.scss.d.ts
  src/app/loadout/loadout-ui/PlugDef.tsx
  src/app/loadout/plug-drawer/Footer.tsx
  src/app/organizer/Columns.tsx
Labels: no changelog

#7271 Better item grouping before LO processing.
  src/app/loadout-builder/process/useProcess.ts
Labels: no changelog

#7297 Optimiser: Move masterwork stat addition to mapping.
  src/app/loadout-builder/process-worker/process.ts
  src/app/loadout-builder/process-worker/tsconfig.json
  src/app/loadout-builder/process-worker/types.ts
  src/app/loadout-builder/process/mappers.ts
Labels: no changelog

#7298 Cleanup old mod assignment algorithm.
  src/app/loadout-builder/generated-sets/CompareDrawer.tsx
  src/app/loadout-builder/generated-sets/GeneratedSet.tsx
  src/app/loadout-builder/mod-assignments.ts
Labels: no changelog

#7302 The Great Spelling Hunt 2.0
  .github/workflows/check-spelling.yml
  .vscode/settings.json
  Gruntfile.js
  config/webpack.js
  cspell-dim-dict.txt
  cspell.json
  src/app/_variables.scss
  src/app/accounts/destiny-account.ts
  src/app/armory/ItemGrid.tsx
  src/app/destiny1/loadout-builder/calculate.ts
  src/app/inventory/bulk-actions.tsx
  src/app/inventory/subclass.ts
  src/app/loadout-builder/LoadoutBuilder.tsx
  src/app/loadout-builder/process-worker/process.ts
  src/app/loadout-builder/process/mappers.ts
  src/app/main.scss
  src/app/search/d1-known-values.ts
  src/app/search/search-filters/freeform.tsx
  src/app/shell/icons/Library.ts
Labels: no changelog

#7308 Webpack tweaks
  config/webpack.js
Labels: no changelog

#7311 Css fix
  .vscode/settings.json
  src/app/dim-ui/StaticPage.m.scss
  src/app/dim-ui/StaticPage.m.scss.d.ts
  src/app/dim-ui/StaticPage.tsx
  src/app/loadout-drawer/LoadoutDrawer.tsx
  src/app/search/FilterHelp.tsx
  src/app/shell/About.tsx
  src/app/shell/Privacy.tsx
  src/app/whats-new/WhatsNew.tsx
Labels: no changelog

#7312 Improved LO item grouping, remove stat-subset items
  cspell-dim-dict.txt
  src/app/loadout-builder/mod-utils.ts
  src/app/loadout-builder/process-worker/process.ts
  src/app/loadout-builder/process/useProcess.ts
  src/app/loadout/mod-utils.ts
  src/app/utils/item-utils.ts
Labels: no changelog

#7309 Loadout page improvements on phone
  src/app/loadout/Loadouts.m.scss
  src/app/loadout/Loadouts.tsx
Labels: Feature: Loadouts, no changelog

#7318 BrowerCheck Utils
  .github/workflows/i18n-bot-download.yml
  cspell-dim-dict.txt
  i18next-scanner.config.js
  package.json
  src/browsercheck-utils.js
  src/browsercheck.js
  src/build-browsercheck-utils.js
  src/index.html
  src/locale/dim.json
Labels: Infrastructure: i18n, i18n, no changelog

#7314 Make Loadout Optimizer 25x faster
  config/i18n.json
  config/webpack.js
  docs/CHANGELOG.md
  src/app/loadout-builder/LoadoutBuilder.m.scss
  src/app/loadout-builder/LoadoutBuilder.m.scss.d.ts
  src/app/loadout-builder/LoadoutBuilder.tsx
  src/app/loadout-builder/generated-sets/utils.ts
  src/app/loadout-builder/process-worker/process.ts
  src/app/loadout-builder/process-worker/set-tracker.ts
  src/app/loadout-builder/process-worker/types.ts
  src/app/loadout-builder/process/mappers.ts
  src/app/loadout-builder/process/useProcess.ts
  src/locale/dim.json
Labels: Feature: Loadout Optimizer

#7319 LO single set bug
  docs/CHANGELOG.md
  src/app/loadout-builder/LoadoutBuilder.tsx
  src/app/loadout-builder/filter/TierSelect.m.scss
  src/app/loadout-builder/filter/TierSelect.m.scss.d.ts
  src/app/loadout-builder/filter/TierSelect.tsx
  src/app/loadout-builder/generated-sets/GeneratedSets.tsx
  src/app/loadout-builder/generated-sets/utils.ts
  src/app/loadout-builder/loadout-builder-reducer.ts
  src/app/loadout-builder/loadout-params.ts
  src/app/loadout-drawer/selectors.ts
Labels: Feature: Loadout Optimizer

#7327 ignore spelling browsercheck-utils.js
  cspell.json
Labels: no changelog

#7322 Tweak loadouts display
  src/app/loadout/Loadouts.m.scss
  src/app/loadout/Loadouts.m.scss.d.ts
  src/app/loadout/Loadouts.tsx
Labels: Feature: Loadouts, no changelog

#7328 Make LO mod searching faster.
  src/app/loadout-builder/process-worker/process-utils.ts
Labels: no changelog

#7329 update package scripts for easier maintenance
  .github/workflows/i18n-bot-download.yml
  .github/workflows/pr-build.yml
  config/webpack.js
  docs/CONTRIBUTING.md
  docs/Docker.md
  package.json
  yarn.lock
Labels: no changelog

#7332 Yarn build updates
  .github/workflows/deploy-beta.yml
  .github/workflows/pr-build.yml
  build/deploy-prod.sh
  config/webpack.js
  package.json
Labels: no changelog

#7323 Fix currentlyCanRoll in the presence of duplicate perks
  docs/CHANGELOG.md
  src/app/inventory/store/sockets.ts
Labels: Feature: Armory

#7326 Apply current search filter to pin/exclude item menus
  docs/CHANGELOG.md
  src/app/loadout-builder/LoadoutBuilder.tsx
  src/app/loadout-builder/filter/LockArmorAndPerks.tsx
Labels: Feature: Loadout Optimizer

#7310 Loadout notes
  config/i18n.json
  docs/CHANGELOG.md
  src/app/dim-api/dim-api-helper.ts
  src/app/dim-api/reducer.ts
  src/app/loadout-builder/LoadoutBuilder.tsx
  src/app/loadout-builder/LoadoutBuilderContainer.tsx
  src/app/loadout-builder/generated-sets/CompareDrawer.tsx
  src/app/loadout-builder/generated-sets/GeneratedSet.tsx
  src/app/loadout-builder/generated-sets/GeneratedSetButtons.tsx
  src/app/loadout-builder/generated-sets/GeneratedSets.tsx
  src/app/loadout-drawer/LoadoutDrawer.tsx
  src/app/loadout-drawer/LoadoutDrawerOptions.tsx
  src/app/loadout/Loadouts.m.scss
  src/app/loadout/Loadouts.m.scss.d.ts
  src/app/loadout/Loadouts.tsx
  src/locale/dim.json
Labels: Feature: Loadouts

#7324 Support "est" stats in total/mean search combiners
  config/i18n.json
  docs/CHANGELOG.md
  src/app/search/search-filters/stats.tsx
  src/locale/dim.json
Labels: Feature: Search
