Repository DestinyItemManager/DIM, pull requests merged in 2021-12, with the labels that each got.

#7342 language is not correct
  cspell.json
  src/browsercheck.js
Labels: no changelog

#7343 Add more information for SelectablePlug
  src/app/loadout/plug-drawer/PlugDrawer.tsx
  src/app/loadout/plug-drawer/PlugSection.tsx
  src/app/loadout/plug-drawer/SelectablePlug.tsx
Labels: no changelog

#7339 LO: Item filter only drops filtering for search filter
  src/app/loadout-builder/item-filter.ts
Labels: no changelog

#7340 Provide a sheet context so press tips dont move around on scroll.
  src/app/dim-ui/PressTip.tsx
  src/app/dim-ui/Sheet.tsx
Labels: no changelog

#7344 Upgrades
  package.json
  yarn.lock
Labels: no changelog

#7345 Implement InsertSocketPlugFree
  src/app/bungie-api/authenticated-fetch.ts
  src/app/bungie-api/http-client.ts
  src/app/bungie-api/rate-limit-config.ts
  src/app/inventory/advanced-write-actions.ts
  src/app/item-popup/ApplyPerkSelection.tsx
  src/app/item-popup/ItemDetails.tsx
  src/app/item-popup/SocketDetailsSelectedPlug.tsx
Labels: no changelog

#7347 Attempt at fixing mobile styles for super icon.
  src/app/loadout-drawer/subclass-drawer/ItemSocketsSubclass.m.scss
  src/app/loadout-drawer/subclass-drawer/ItemSocketsSubclass.m.scss.d.ts
  src/app/loadout-drawer/subclass-drawer/ItemSocketsSubclass.tsx
  src/app/loadout-drawer/subclass-drawer/Subclass.m.scss
Labels: no changelog

#7354 Put instructions inline for LO on mobile
  src/app/loadout-builder/LoadoutBuilder.tsx
  src/app/loadout-builder/filter/LockArmorAndPerks.m.scss
  src/app/loadout-builder/filter/LockArmorAndPerks.m.scss.d.ts
  src/app/loadout-builder/filter/LockArmorAndPerks.tsx
Labels: Feature: Loadout Optimizer, no changelog

#7367 simplify string copying
  src/app/utils/util.ts
Labels: no changelog

#7359 Use plug def in more places.
  src/app/loadout/Loadouts.tsx
  src/app/loadout/loadout-ui/Mod.tsx
  src/app/loadout/loadout-ui/PlugDef.m.scss
  src/app/loadout/loadout-ui/PlugDef.m.scss.d.ts
  src/app/loadout/loadout-ui/PlugDef.tsx
Labels: no changelog

#7370 More loadout fixes
  src/app/loadout-builder/LoadoutBuilderContainer.tsx
  src/app/loadout-drawer/LoadoutDrawer.tsx
  src/app/loadout/Loadouts.tsx
Labels: Feature: Loadouts, no changelog

#7368 Equip mods in Loadouts
  config/i18n.json
  src/app/inventory/MoveNotifications.tsx
  src/app/inventory/actions.ts
  src/app/inventory/advanced-write-actions.ts
  src/app/inventory/reducer.ts
  src/app/item-popup/SocketDetailsSelectedPlug.tsx
  src/app/loadout-builder/generated-sets/CompareDrawer.tsx
  src/app/loadout-builder/generated-sets/GeneratedSet.tsx
  src/app/loadout-drawer/loadout-apply.ts
  src/app/loadout-drawer/loadout-utils.ts
  src/app/loadout/loadout-ui/Sockets.tsx
  src/app/loadout/mod-assignment-drawer/ModAssignmentDrawer.tsx
  src/app/loadout/mod-assignment-drawer/selectors.ts
  src/app/loadout/mod-utils.ts
  src/app/notifications/Notification.m.scss
  src/app/utils/socket-utils.ts
  src/locale/dim.json
Labels: no changelog

#7351 Add masked icon and update manifest for pwa
  icons/build_icons.js
  icons/release/android-chrome-mask-512x512-6-2018.png
  src/app/App.tsx
  src/manifest-webapp-6-2018.json
Labels: no changelog

#7358 Various render key improvements/additions.
  src/app/loadout-builder/filter/LockArmorAndPerks.tsx
  src/app/loadout-builder/generated-sets/CompareDrawer.tsx
  src/app/loadout-drawer/subclass-drawer/ItemSocketsSubclass.tsx
  src/app/loadout/mod-assignment-drawer/ModAssignmentDrawer.tsx
  src/app/loadout/mod-utils.ts
  src/app/loadout/plug-drawer/Footer.tsx
Labels: no changelog

#7383 Fix raid mod descriptions.
  src/app/loadout/plug-drawer/SelectablePlug.m.scss
  src/app/loadout/plug-drawer/SelectablePlug.m.scss.d.ts
  src/app/loadout/plug-drawer/SelectablePlug.tsx
Labels: no changelog

#7385 Guard loadout mod application with canInsertMod
  config/i18n.json
  src/app/inventory/advanced-write-actions.ts
  src/app/loadout-drawer/loadout-apply.ts
Labels: no changelog

#7382 Optimise mod assignment so we don't need to clear mods first.
  src/app/loadout-builder/generated-sets/CompareDrawer.tsx
  src/app/loadout-builder/generated-sets/GeneratedSet.tsx
  src/app/loadout-drawer/loadout-apply.ts
  src/app/loadout/mod-assignment-drawer/ModAssignmentDrawer.tsx
  src/app/loadout/mod-utils.ts
Labels: no changelog

#7380 remove warning and adjust "already there" mods logic
  src/app/loadout-drawer/SavedMods.m.scss
  src/app/loadout-drawer/SavedMods.m.scss.d.ts
  src/app/loadout-drawer/SavedMods.tsx
  src/app/loadout-drawer/loadout-apply.ts
Labels: no changelog

#7397 Fix getting socket by index.
  src/app/loadout-drawer/loadout-apply.ts
Labels: no changelog

#7398 Revert adding mods to successful when skipped.
  src/app/loadout-drawer/loadout-apply.ts
Labels: no changelog

#7399 Refresh characters after applying all loadout changes.
  src/app/inventory/MoveNotifications.tsx
  src/app/loadout-drawer/loadout-apply.ts
Labels: no changelog

#7403 Trust Bungie's response from InsertPlug
  src/app/inventory/advanced-write-actions.ts
  src/app/loadout-drawer/loadout-apply.ts
Labels: no changelog

#7413 Improve error messaging for insertplugs
  config/i18n.json
  src/app/inventory/advanced-write-actions.ts
  src/app/loadout-drawer/loadout-apply.ts
  src/locale/dim.json
Labels: no changelog

#7417 Use helper to index into sockets rather than indexing into the list
  src/app/loadout-drawer/loadout-apply.ts
Labels: no changelog

#7419 Don't count clearing mods as "successful mods"
  src/app/loadout-drawer/loadout-apply.ts
Labels: no changelog

#7424 Remove double notification on plug insert
  config/i18n.json
  src/app/inventory/advanced-write-actions.ts
  src/app/item-popup/SocketDetailsSelectedPlug.tsx
  src/app/loadout-drawer/loadout-apply.ts
  src/locale/dim.json
Labels: no changelog

#7432 spelling
  src/app/inventory/advanced-write-actions.ts
  src/app/loadout/mod-utils.ts
Labels: no changelog

#7433 Add src/data to prettier ignore.
  .prettierignore
Labels: no changelog

#7440 implement assignment strategy that leaves mods alone if they can remain
  src/app/loadout-builder/generated-sets/CompareDrawer.tsx
  src/app/loadout-builder/generated-sets/GeneratedSet.tsx
  src/app/loadout-drawer/loadout-apply.ts
  src/app/loadout-drawer/loadout-types.ts
  src/app/loadout/mod-assignment-drawer/ModAssignmentDrawer.tsx
  src/app/loadout/mod-assignment-utils.ts
  src/app/loadout/mod-utils.ts
Labels: no changelog

#7445 dynamic replacer hook
  src/app/dim-ui/RichDestinyText.tsx
  src/app/progress/CrucibleRank.tsx
Labels: no changelog

#7430 Remove ability cooldowns in stats tooltips.
  config/webpack.js
Labels: no changelog

#7429 Add show mod placements button to loadouts page.
  src/app/loadout/Loadouts.m.scss
  src/app/loadout/Loadouts.m.scss.d.ts
  src/app/loadout/Loadouts.tsx
  src/app/loadout/mod-assignment-drawer/ModAssignmentDrawer.tsx
Labels: no changelog

#7448 Add mods with +Equipped, and save subclass stuff with "Create From Equipped"
  docs/CHANGELOG.md
  src/app/inventory/store/override-sockets.ts
  src/app/loadout-drawer/LoadoutDrawer.tsx
  src/app/loadout-drawer/LoadoutDrawerBucket.tsx
  src/app/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/loadout-drawer/LoadoutPopup.tsx
  src/app/loadout-drawer/loadout-apply.ts
  src/app/loadout-drawer/loadout-drawer-reducer.ts
  src/app/loadout-drawer/loadout-utils.ts
  src/app/loadout/Loadouts.tsx
Labels: Feature: Loadouts

#7454 Carefully rearrange dependencies so tests don't have to pull in fetch
  src/app/inventory/store/override-sockets.ts
  src/app/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/loadout-drawer/loadout-utils.ts
  src/app/store/store.ts
Labels: no changelog

#7461 browsercheck ensure lang
  src/browsercheck.js
Labels: no changelog

#7464 stop showing extraneous text in stasis aspects
  src/app/loadout/plug-drawer/SelectablePlug.tsx
Labels: no changelog

#7467 Mod picker grouping fix
  src/app/loadout-drawer/SavedMods.tsx
  src/app/loadout-drawer/subclass-drawer/SubclassPlugDrawer.tsx
  src/app/loadout/ModPicker.tsx
  src/app/loadout/mod-utils.ts
  src/app/loadout/plug-drawer/PlugDrawer.tsx
  src/app/loadout/plug-drawer/PlugSection.tsx
Labels: no changelog

#7480 Update compare-buttons.tsx
  src/app/compare/compare-buttons.tsx
Labels: no changelog

#7485 preferred locale fix
  src/browsercheck.js
Labels: no changelog

#7481 Hide cost overlay for Stasis fragments
  src/app/inventory/ItemIcon.tsx
Labels: no changelog

#7495 Some cleanup in the plug drawer.
  src/app/loadout/plug-drawer/Footer.m.scss
  src/app/loadout/plug-drawer/Footer.m.scss.d.ts
  src/app/loadout/plug-drawer/Footer.tsx
  src/app/loadout/plug-drawer/PlugDrawer.tsx
  src/app/loadout/plug-drawer/PlugSection.tsx
Labels: no changelog

#7494 Remove react router types.
  package.json
  yarn.lock
Labels: no changelog

#7514 Remove parallelism in applying mods to a single item
  src/app/loadout-drawer/loadout-apply.ts
Labels: no changelog

#7511 Custom error messages for some confusing B.net errors
  config/i18n.json
  src/app/bungie-api/bungie-service-helper.ts
  src/app/loadout-drawer/loadout-apply.ts
  src/locale/dim.json
Labels: no changelog

#7518 adjust compare stat bars to account for fluctuating item names
  src/app/compare/CompareStat.m.scss
Labels: no changelog

#7521 Assume browser support if iOS PWA/APP
  src/browsercheck.js
Labels: no changelog

#7520 Remove some feature flags
  config/webpack.js
  src/app/loadout-builder/LoadoutBuilder.tsx
  src/app/loadout-builder/filter/TierSelect.tsx
  src/app/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/loadout-drawer/LoadoutDrawerOptions.tsx
  src/app/loadout-drawer/LoadoutPopup.tsx
  src/app/shell/Destiny.tsx
  src/app/shell/Header.tsx
  src/global.d.ts
Labels: no changelog

#7503 Better ability handling in the subclass drawer.
  src/app/loadout-drawer/subclass-drawer/SubclassPlugDrawer.tsx
  src/app/loadout/ModPicker.tsx
  src/app/loadout/plug-drawer/Footer.tsx
  src/app/loadout/plug-drawer/PlugDrawer.tsx
  src/app/loadout/plug-drawer/PlugSection.tsx
  src/app/loadout/plug-drawer/SelectablePlug.m.scss
  src/app/loadout/plug-drawer/SelectablePlug.tsx
Labels: no changelog

#7508 Add DimPlugSets to DimSockets.
  src/app/inventory/item-types.ts
  src/app/inventory/store/d2-item-factory.ts
  src/app/inventory/store/sockets.ts
  src/app/records/plugset-helpers.ts
Labels: no changelog

#7528 Fix for conditional mod assignment.
  src/app/loadout/mod-assignment-utils.ts
Labels: no changelog

#7522 Add apple-app-site-association to handle deep links
  build/purge-cloudflare.sh
  config/.well-known/android-config.beta.json
  config/.well-known/android-config.json
  config/.well-known/apple-config.json
  config/webpack.js
Labels: no changelog

#7532 switch to natural orientation
  src/manifest-webapp-6-2018.json
Labels: no changelog

#7535 Force uninstanced items to never have a wishlist roll
  src/app/wishlists/selectors.ts
  src/app/wishlists/wishlists.ts
Labels: Feature: Wish List, no changelog

#7541 language detection fix
  src/browsercheck.js
Labels: no changelog

#7523 Use DimPlugSets.
  src/app/inventory/store/energy.ts
  src/app/item-popup/EnergyMeter.tsx
  src/app/item-popup/SocketDetails.tsx
  src/app/loadout-builder/filter/ExoticPicker.tsx
  src/app/loadout-builder/item-filter.ts
  src/app/loadout-drawer/subclass-drawer/SubclassPlugDrawer.tsx
  src/app/loadout/ModPicker.tsx
  src/app/loadout/armor-upgrade-utils.ts
  src/app/loadout/mod-assignment-utils.ts
  src/app/records/plugset-helpers.ts
Labels: no changelog

#7530 Default to current store in LO when loading a global loadout
  src/app/loadout-builder/loadout-builder-reducer.ts
Labels: Feature: Loadouts, no changelog

#7536 Never show badge for subclass
  src/app/inventory/BadgeInfo.tsx
Labels: no changelog

#7548 Add plug subtype to tooltips
  src/app/dim-ui/PressTip.m.scss
  src/app/item-popup/ItemPerksList.tsx
  src/app/item-popup/PlugTooltip.tsx
  src/app/item-popup/SocketDetails.tsx
  src/app/loadout/loadout-ui/Mod.tsx
Labels: no changelog

#7551 Upgrades
  package.json
  src/app/loadout-builder/LoadoutBuilderContainer.tsx
  yarn.lock
Labels: no changelog

#7546 PlugDrawer cleanup
  src/app/destiny1/loadout-builder/LoadoutBuilderLockPerk.tsx
  src/app/item-popup/SocketDetails.tsx
  src/app/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/loadout-drawer/subclass-drawer/SubclassPlugDrawer.tsx
  src/app/loadout/ModPicker.tsx
  src/app/loadout/mod-utils.ts
  src/app/loadout/plug-drawer/PlugDrawer.tsx
  src/app/loadout/plug-drawer/PlugSection.tsx
  src/app/loadout/plug-drawer/SelectablePlug.tsx
  src/app/records/plugset-helpers.ts
  src/app/settings/SortOrderEditor.tsx
Labels: no changelog

#7553 Fix for loadouts that have armour 1.0 items and mods.
  src/app/loadout-drawer/loadout-apply.ts
  src/app/loadout/mod-assignment-utils.ts
Labels: no changelog

#7550 Fix perk search for languages with accents
  docs/CHANGELOG.md
  src/app/compare/compare-buttons.tsx
  src/app/organizer/Columns.tsx
  src/app/search/search-filters/freeform.tsx
Labels: Feature: Search, i18n

#7567 Added streakHash for Strange Favor (Dares of Eternity)
  src/app/progress/Ranks.tsx
Labels: no changelog

#7555 Split loadout out of loadout row.
  src/app/loadout/LoadoutView.m.scss
  src/app/loadout/LoadoutView.m.scss.d.ts
  src/app/loadout/LoadoutView.tsx
  src/app/loadout/Loadouts.m.scss
  src/app/loadout/Loadouts.m.scss.d.ts
  src/app/loadout/Loadouts.tsx
Labels: no changelog

#7565 Better DimLoadoutItem.
  src/app/loadout-drawer/loadout-item-conversion.ts
  src/app/loadout-drawer/loadout-types.ts
Labels: no changelog

#7569 Fix loadout view placeholder.
  src/app/loadout/loadout-ui/LoadoutItemCategorySection.m.scss
Labels: no changelog

#7573 missed contextList
  src/app/loadout/loadout-ui/LoadoutItemCategorySection.tsx
  src/locale/dim.json
Labels: no changelog

#7554 Sheet disable
  src/app/compare/Compare.tsx
  src/app/dim-ui/PressTip.tsx
  src/app/dim-ui/Sheet.m.scss
  src/app/dim-ui/Sheet.m.scss.d.ts
  src/app/dim-ui/Sheet.tsx
  src/app/loadout-drawer/LoadoutDrawer.tsx
  src/app/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/loadout-drawer/LoadoutDrawerOptions.tsx
  src/app/loadout/ModPicker.tsx
  src/app/loadout/mod-assignment-drawer/ModAssignmentDrawer.tsx
  src/app/loadout/plug-drawer/PlugDrawer.tsx
  src/app/search/SearchResults.tsx
Labels: no changelog

#7539 Handle scrollbars in page menus better
  src/app/dim-ui/PageWithMenu.m.scss
  src/app/dim-ui/PageWithMenu.m.scss.d.ts
  src/app/dim-ui/PageWithMenu.tsx
Labels: no changelog

#7574 Add more docs to process mod assignment algorithm.
  src/app/loadout-builder/process-worker/process-utils.ts
Labels: no changelog

#7556 Plumb through the store ID as context for loadout editing
  src/app/destiny1/loadout-builder/GeneratedSet.tsx
  src/app/item-triage/ItemTriage.tsx
  src/app/loadout-builder/generated-sets/GeneratedSet.tsx
  src/app/loadout-drawer/LoadoutDrawer.tsx
  src/app/loadout-drawer/LoadoutPopup.tsx
  src/app/loadout-drawer/loadout-drawer-reducer.ts
  src/app/loadout-drawer/loadout-events.ts
  src/app/loadout/Loadouts.tsx
Labels: Feature: Loadouts, no changelog

#7580 Filter out nonexistant mods
  src/app/loadout-drawer/loadout-apply.ts
Labels: no changelog

#7568 Use LoadoutView in compare drawer.
  src/app/loadout-builder/LoadoutBuilder.tsx
  src/app/loadout-builder/generated-sets/CompareDrawer.m.scss
  src/app/loadout-builder/generated-sets/CompareDrawer.m.scss.d.ts
  src/app/loadout-builder/generated-sets/CompareDrawer.tsx
  src/app/loadout/LoadoutView.tsx
  src/app/loadout/loadout-ui/LoadoutItemCategorySection.tsx
Labels: no changelog

#7582 fix error where plugs without tracking would have partial tracking …
  src/app/loadout-drawer/loadout-apply-state.ts
Labels: no changelog

#7584 allow inventory sort by element
  src/app/settings/SettingsPage.tsx
  src/app/shell/filters.ts
Labels: no changelog

#7585 Handle subclasses properly in loadouts and socket overrides application
  src/app/item-picker/ItemPicker.tsx
  src/app/item-picker/item-picker.ts
  src/app/loadout-drawer/loadout-apply.ts
  src/app/loadout/LoadoutView.tsx
  src/app/loadout/item-utils.ts
Labels: no changelog

#7607 Fix some confusion around whether existing loadout is being edited
  src/app/loadout-drawer/LoadoutDrawer.tsx
  src/app/loadout-drawer/loadout-drawer-reducer.ts
Labels: no changelog

#7601 Hide the support and shop buttons on the iOS app
  src/app/shell/About.tsx
Labels: no changelog
