Repository DestinyItemManager/DIM, pull requests merged in 2022-05, with the labels that each got.

#8354 add more rich text. always more. forever.
  docs/CHANGELOG.md
  src/app/item-popup/ItemDescription.tsx
Labels: Changelog-Applied

#8357 Upgrades
  config/webpack.js
  package.json
  src/app/item-picker/ItemPicker.tsx
  src/app/organizer/ItemTable.tsx
  src/app/settings/Spreadsheets.tsx
  src/app/settings/Troubleshooting.tsx
  src/app/storage/ImportExport.tsx
  src/app/store-stats/AccountCurrencies.test.tsx
  yarn.lock
Labels: Changelog-None, Changelog-Missing

#8360 Improved recoil stat display
  docs/CHANGELOG.md
  src/app/item-popup/RecoilStat.tsx
Labels: Changelog-Applied

#8358 React 18
  config/webpack.js
  package.json
  src/app/Root.tsx
  yarn.lock
Labels: Changelog-Missing

#8365 Configure VSCode file nesting
  .vscode/settings.json
Labels: Changelog-Missing

#8364 Minor upgrades
  package.json
  yarn.lock
Labels: Changelog-Missing

#8368 Remove dead code and unnecessary exports
  src/app/App.tsx
  src/app/dim-ui/DestinyTooltipText.tsx
  src/app/dim-ui/SpecialtyModSlotIcon.tsx
  src/app/dim-ui/svgs/BucketIcon.tsx
  src/app/inventory/subclass.ts
  src/app/item-triage/triage-utils.tsx
  src/app/loadout-drawer/loadout-drawer-reducer.ts
  src/app/material-counts/MaterialCountsWrappers.tsx
  src/app/records/presentation-nodes.ts
  src/app/search/search-filters/freeform.tsx
  src/app/search/search-utils.ts
  src/app/settings/components.ts
Labels: Changelog-Missing

#8370 Do away with inventory size stat
  config/i18n.json
  src/app/inventory/store/stats.ts
  src/app/organizer/Columns.tsx
  src/app/search/__snapshots__/autocomplete.test.ts.snap
  src/app/search/__snapshots__/search-utils.test.ts.snap
  src/app/search/d2-known-values.ts
  src/locale/en.json
Labels: Changelog-None, Changelog-Missing

#8369 Clean up stats display a bit
  src/app/item-popup/ItemStat.tsx
  src/app/organizer/Columns.tsx
Labels: Changelog-Missing

#8371 Fix color grading for ]99%, 100%[ interval
  src/app/shell/formatters.ts
Labels: Changelog-None

#8363 Switch to createRoot ("Concurrent Mode")
  src/Index.tsx
Labels: Changelog-Missing

#8367 Remove ability cooldowns code
  config/webpack.js
  src/app/loadout-builder/generated-sets/GeneratedSet.tsx
  src/app/loadout-builder/generated-sets/SetStats.tsx
  src/app/loadout/loadout-edit/LoadoutEditBucket.tsx
  src/app/loadout/loadout-ui/LoadoutItemCategorySection.tsx
  src/app/loadout/mod-assignment-drawer/ModAssignmentDrawer.tsx
  src/app/store-stats/CharacterStats.tsx
  src/app/store-stats/StatTooltip.m.scss
  src/app/store-stats/StatTooltip.m.scss.d.ts
  src/app/store-stats/StatTooltip.tsx
  src/app/store-stats/StoreStats.tsx
  src/app/utils/stat-effect-utils.ts
  src/global.d.ts
Labels: Changelog-Missing

#8373 Tweak presstip arrow placement
  src/app/dim-ui/PressTip.m.scss
Labels: Changelog-Missing

#8379 Bump over sheet close button on Armory sheet
  src/app/armory/ArmorySheet.m.scss
Labels: Changelog-Missing

#8380 Add code snippet for importing CSS module file
  .vscode/dim.code-snippets
Labels: Changelog-Missing

#8375 Fix popper jank
  src/app/dim-ui/PressTip.m.scss
  src/app/dim-ui/usePopper.ts
  src/app/item-popup/DesktopItemActions.tsx
  src/app/item-popup/ItemPopup.m.scss
  src/app/item-popup/ItemPopup.tsx
  src/app/item-popup/sidecar-popper-modifier.ts
Labels: Changelog-None, Changelog-Missing

#8382 Clean up perks
  src/app/inventory/item-types.ts
  src/app/inventory/store/d1-item-factory.ts
  src/app/inventory/store/d2-item-factory.ts
  src/app/item-popup/ItemDetails.tsx
  src/app/item-popup/ItemPerks.tsx
  src/app/progress/milestone-items.ts
  src/app/search/search-filters/freeform.tsx
Labels: Changelog-Missing

#8383 Automatically add enhanced versions of perks to Wishlisted Rolls because we match them too
  src/app/armory/wishlist-collapser.ts
Labels: Changelog-None

#8324 LO: Replace "Lock Element: Masterworked" with "In (Other) Loadouts" option
  config/i18n.json
  docs/CHANGELOG.md
  src/app/loadout-builder/LoadoutBuilder.tsx
  src/app/loadout-builder/filter/EnergyOptions.tsx
  src/app/loadout-builder/generated-sets/GeneratedSet.tsx
  src/app/loadout-builder/generated-sets/GeneratedSets.tsx
  src/app/loadout-builder/item-filter.ts
  src/app/loadout-builder/process-utils.test.ts
  src/app/loadout-builder/process/mappers.test.ts
  src/app/loadout-builder/process/mappers.ts
  src/app/loadout-builder/process/useProcess.ts
  src/app/loadout-builder/types.ts
  src/app/loadout-drawer/loadout-apply.ts
  src/app/loadout/armor-upgrade-utils.ts
  src/app/loadout/mod-assignment-drawer/ModAssignmentDrawer.tsx
  src/app/loadout/mod-assignment-utils.ts
  src/app/loadout/mod-utils.ts
  src/locale/en.json
Labels: Changelog-Applied

#8385 Optimize searching and perk generation for freeform text searches
  src/app/search/search-filters/freeform.tsx
Labels: Changelog-Missing

#8372 Use useDeferredValue to speed up autocompleter interactions
  src/app/search/SearchBar.tsx
Labels: Changelog-None, Changelog-Missing

#8389 Replace _.uniq, _.uniqBy
  .eslintrc
  src/app/armory/wishlist-collapser.ts
  src/app/destiny1/loadout-builder/D1LoadoutBuilder.tsx
  src/app/destiny1/loadout-builder/utils.ts
  src/app/destiny1/loadout-drawer/LoadoutDrawerOptions.tsx
  src/app/dim-api/reducer.ts
  src/app/inventory/note-hashtags.ts
  src/app/inventory/store/d1-item-factory.ts
  src/app/item-picker/ItemPicker.tsx
  src/app/loadout-builder/filter/ExoticPicker.tsx
  src/app/loadout/ModPicker.tsx
  src/app/loadout/SubclassPlugDrawer.tsx
  src/app/organizer/ItemTable.tsx
  src/app/progress/Milestones.tsx
  src/app/records/Records.tsx
  src/app/search/autocomplete.ts
  src/app/search/search-filters/freeform.tsx
  src/app/settings/SettingsPage.tsx
  src/app/shell/reducer.ts
  src/app/utils/util.ts
  src/app/vendors/Vendor.tsx
  src/app/vendors/VendorItems.tsx
Labels: Changelog-Missing

#8390 Don't warn about missing items due to Vault not having access to subclasses
  docs/CHANGELOG.md
  src/app/loadout-drawer/loadout-utils.ts
Labels: Changelog-Applied

#8378 Update wish list docs, add wish list line to Armory view
  config/i18n.json
  docs/COMMUNITY_CURATIONS.md
  src/app/armory/Armory.tsx
  src/app/armory/Links.tsx
  src/app/armory/WishListEntry.m.scss
  src/app/armory/WishListEntry.m.scss.d.ts
  src/app/armory/WishListEntry.tsx
  src/locale/en.json
Labels: Changelog-Missing

#8376 Dropdown keyboard accessibility
  src/app/dim-ui/Dropdown.tsx
  src/app/dim-ui/Select.tsx
Labels: Changelog-None, Changelog-Missing

#8377 Fix extra padding around archetype socket for armor
  src/app/item-popup/ItemSocketsGeneral.tsx
Labels: Changelog-None, Changelog-Missing

#8381 Account for already-equipped items in search transfers
  src/app/loadout-drawer/auto-loadouts.ts
Labels: Changelog-Missing

#8395 Remove memoizeOne
  package.json
  src/app/destiny1/vendors/vendor.service.ts
  src/app/manifest/manifest-service-json.ts
  src/app/search/SearchBar.tsx
  src/app/search/autocomplete.ts
  yarn.lock
Labels: Changelog-Missing

#8405 Fix some sentry issues from Season of the Haunted
  src/app/inventory/d2-stores.ts
  src/app/inventory/selectors.ts
  src/app/progress/Objective.tsx
Labels: Changelog-Missing

#8409 Add airborne effectiveness stat
  docs/CHANGELOG.md
  src/app/inventory/store/stats.ts
Labels: Changelog-Applied

#8397 Sort items perf
  src/app/search/search-filter.ts
  src/app/settings/SettingsPage.tsx
  src/app/settings/item-sort.ts
  src/app/shell/item-comparators.ts
Labels: Changelog-Missing

#8402 Use useDeferredValue to speed up item picker searches
  src/app/infuse/InfusionFinder.tsx
  src/app/item-picker/ItemPicker.tsx
  src/app/search/SearchBar.tsx
Labels: Changelog-Missing

#8414 Solar 3.0: Display selected Super icon and hide fragment costs
  docs/CHANGELOG.md
  src/app/inventory/InventoryItem.tsx
  src/app/inventory/ItemIcon.tsx
Labels: Changelog-Applied

#8415 Remove Deepsight Resonant Element search filters and tooltip
  docs/CHANGELOG.md
  src/app/dim-ui/WeaponDeepsightInfo.m.scss
  src/app/dim-ui/WeaponDeepsightInfo.m.scss.d.ts
  src/app/dim-ui/WeaponDeepsightInfo.tsx
  src/app/inventory/item-types.ts
  src/app/inventory/store/d2-item-factory.ts
  src/app/inventory/store/deepsight.ts
  src/app/search/search-filters/sockets.tsx
Labels: Changelog-Applied

#8407 Use a temp container to avoid style recalcs
  src/app/armory/ItemGrid.tsx
  src/app/dim-ui/PressTip.tsx
  src/app/item-popup/ItemPopupHeader.tsx
  src/app/item-popup/ItemSocketsGeneral.tsx
  src/app/item-popup/ItemSocketsWeapons.tsx
  src/app/loadout-builder/LoadoutBuilder.tsx
  src/app/loadout-builder/filter/LockArmorAndPerks.tsx
  src/app/loadout/Loadouts.tsx
  src/app/loadout/fashion/FashionDrawer.tsx
  src/app/loadout/loadout-edit/LoadoutEdit.tsx
  src/app/loadout/loadout-edit/LoadoutEditBucket.tsx
  src/app/loadout/loadout-ui/LoadoutMods.tsx
  src/app/loadout/mod-assignment-drawer/ModAssignmentDrawer.tsx
  src/app/search/MainSearchBarActions.tsx
  src/app/search/SearchBar.tsx
  src/app/shell/Header.tsx
  src/app/utils/temp-container.ts
  src/app/utils/util.ts
  src/index.html
Labels: Changelog-Missing

#8403 Memoize components
  src/app/character-tile/CharacterTile.tsx
  src/app/character-tile/StoreHeading.scss
  src/app/character-tile/StoreHeading.tsx
  src/app/compare/CompareItem.tsx
Labels: Changelog-Missing

#8400 Remove ceaser-easing
  package.json
  src/app/_variables.scss
  src/app/dim-ui/Loading.m.scss
  src/app/farming/farming.scss
  src/app/loadout-builder/LoadoutBuilder.m.scss
  src/app/shell/Header.m.scss
Labels: Changelog-Missing

#8394 Swap in sass for node-sass
  package.json
  yarn.lock
Labels: Changelog-Missing

#8398 Notes tag perf
  config/webpack.js
  src/app/item-popup/NotesArea.m.scss
  src/app/item-popup/NotesArea.tsx
  src/app/main.scss
  src/app/utils/textarea-caret.ts
Labels: Changelog-Missing

#8417 Shorten Airborne Effectiveness stat name in compare/popup
  config/i18n.json
  src/app/item-popup/ItemStat.tsx
  src/app/organizer/Columns.tsx
  src/locale/en.json
Labels: Changelog-Missing

#8423 Upgrades
  package.json
  src/app/Root.tsx
  yarn.lock
Labels: Changelog-Missing

#8420 Deepsight pattern features
  config/i18n.json
  docs/CHANGELOG.md
  src/app/dim-ui/WeaponDeepsightInfo.m.scss
  src/app/dim-ui/WeaponDeepsightInfo.m.scss.d.ts
  src/app/dim-ui/WeaponDeepsightInfo.tsx
  src/app/inventory/ItemIcon.m.scss
  src/app/inventory/ItemIcon.m.scss.d.ts
  src/app/inventory/ItemIcon.tsx
  src/app/inventory/d2-stores.ts
  src/app/inventory/item-types.ts
  src/app/inventory/store/crafted.ts
  src/app/inventory/store/d1-item-factory.ts
  src/app/inventory/store/d2-item-factory.ts
  src/app/inventory/store/deepsight.ts
  src/app/inventory/store/patterns.ts
  src/app/item-popup/ItemDetails.tsx
  src/app/progress/milestone-items.ts
  src/app/records/Records.tsx
  src/app/records/presentation-nodes.ts
  src/app/search/__snapshots__/search-config.test.ts.snap
  src/app/search/search-filters/known-values.tsx
  src/app/search/search-filters/sockets.tsx
  src/app/shell/item-comparators.ts
  src/locale/en.json
Labels: Changelog-Applied

#8425 Use layout effect to set sheet height
  src/app/dim-ui/Sheet.tsx
Labels: Changelog-Missing

#8422 Further sort auto loadouts to leave what's already there, there
  src/app/loadout-drawer/auto-loadouts.ts
Labels: Changelog-Missing

#8432 Triage tab fixes for classified items and slug shotguns
  docs/CHANGELOG.md
  src/app/item-triage/ItemTriage.tsx
  src/app/item-triage/triage-utils.tsx
  src/app/search/search-filters/known-values.tsx
Labels: Changelog-Applied

#8429 Reduce a lot of store subscriptions
  src/app/inventory/BadgeInfo.tsx
Labels: Changelog-Missing
