Repository DestinyItemManager/DIM, pull requests merged in 2022-07, with the labels that each got.

#8530 Move tags down 1px
  src/app/inventory/InventoryItem.m.scss
Labels: Changelog-Missing

#8541 Stream Deck: clean up settings, add changelog
  config/i18n.json
  docs/CHANGELOG.md
  src/app/stream-deck/StreamDeckSettings/StreamDeckSettings.m.scss
  src/app/stream-deck/StreamDeckSettings/StreamDeckSettings.m.scss.d.ts
  src/app/stream-deck/StreamDeckSettings/StreamDeckSettings.tsx
  src/locale/en.json
Labels: Changelog-Applied

#8542 Upgrades
  package.json
  src/data/webfonts/fa-brands-400.ttf
  src/data/webfonts/fa-brands-400.woff2
  src/data/webfonts/fa-regular-400.ttf
  src/data/webfonts/fa-regular-400.woff2
  src/data/webfonts/fa-solid-900.ttf
  src/data/webfonts/fa-solid-900.woff2
  yarn.lock
Labels: Changelog-Missing

#8540 Keep community perk text in line with the rest of the tooltip
  src/app/item-popup/PlugTooltip.m.scss
Labels: Changelog-Missing

#8545 Enable Clarity descriptions for release version
  config/webpack.js
  docs/CHANGELOG.md
Labels: Changelog-Applied

#8553 Revert "Upgrade body-scroll-lock"
  package.json
  yarn.lock
Labels: Changelog-Missing

#8552 Less connect
  src/app/inventory/ConnectedInventoryItem.tsx
  src/app/item-picker/ItemPicker.tsx
  src/app/item-popup/SocketDetails.tsx
  src/app/loadout-builder/LoadoutBuilder.tsx
  src/app/loadout-drawer/selectors.ts
  src/app/loadout/loadout-menu/LoadoutPopup.tsx
  src/app/organizer/ItemTable.tsx
  src/app/progress/Progress.tsx
  src/app/search/MainSearchBarActions.tsx
  src/app/search/MainSearchBarMenu.tsx
  src/app/search/SearchResults.tsx
  src/app/search/search-filter.ts
  src/app/vendors/SingleVendor.tsx
  src/app/vendors/Vendors.tsx
Labels: Changelog-Missing

#8085 Catalyst search filters
  config/cspell/bungie-dict.txt
  config/cspell/dim-dict.txt
  config/cspell/dim-username-dict.txt
  config/i18n.json
  docs/CHANGELOG.md
  src/app/inventory/d2-stores.ts
  src/app/inventory/item-types.ts
  src/app/inventory/store/catalyst.ts
  src/app/inventory/store/d2-item-factory.ts
  src/app/item-popup/ItemSocketsWeapons.tsx
  src/app/search/__snapshots__/search-config.test.ts.snap
  src/app/search/search-filters/sockets.tsx
  src/locale/en.json
Labels: Feature: Search, Changelog-Applied
