Repository DestinyItemManager/DIM, pull requests merged in 2022-06, with the labels that each got.

#8426 Fix item index generation logic
  src/app/inventory/store/item-index.ts
Labels: Changelog-Missing

#8427 Explicitly model "instanced" on items
  src/app/bungie-api/destiny2-api.ts
  src/app/inventory/actions.ts
  src/app/inventory/bulk-actions.tsx
  src/app/inventory/dim-item-info.ts
  src/app/inventory/item-types.ts
  src/app/inventory/reducer.ts
  src/app/inventory/store/d1-item-factory.ts
  src/app/inventory/store/d2-item-factory.ts
  src/app/item-actions/ItemActionsDropdown.tsx
  src/app/item-feed/TagButtons.tsx
  src/app/item-popup/ItemPopupContainer.tsx
  src/app/item-popup/ItemTagHotkeys.tsx
  src/app/item-popup/ItemTagSelector.tsx
  src/app/item-popup/NotesArea.tsx
  src/app/item-popup/SocketDetailsSelectedPlug.tsx
  src/app/organizer/ItemTable.tsx
  src/app/progress/milestone-items.ts
  src/app/shell/item-comparators.ts
  src/app/utils/item-utils.ts
  src/app/vendors/vendor-item.ts
  src/app/wishlists/selectors.ts
  src/app/wishlists/wishlists.ts
Labels: Changelog-Missing

#8442 Add currencies to materials popup, move currencies to inventory on mobile
  src/app/inventory-page/PhoneStores.tsx
  src/app/material-counts/MaterialCounts.tsx
  src/app/material-counts/MaterialCountsWrappers.m.scss
  src/app/material-counts/MaterialCountsWrappers.m.scss.d.ts
  src/app/material-counts/MaterialCountsWrappers.tsx
Labels: Changelog-Missing

#8392 RFC: Display the 'name' of a saved search query within the search results
  docs/CHANGELOG.md
  src/app/dim-ui/KeyHelp.m.scss
  src/app/search/SearchBar.m.scss
  src/app/search/SearchBar.m.scss.d.ts
  src/app/search/SearchBar.tsx
  src/app/search/__snapshots__/autocomplete.test.ts.snap
  src/app/search/autocomplete.test.ts
  src/app/search/autocomplete.ts
  src/app/search/query-parser.ts
Labels: Changelog-Applied

#8452 Fix instanced item determination
  docs/CHANGELOG.md
  src/app/inventory/store/d2-item-factory.ts
Labels: Changelog-Applied

#8453 Upgrades
  package.json
  src/app/i18n.ts
  yarn.lock
Labels: Changelog-Missing

#8459 Temp: Disable drag and drop on portrait
  src/app/inventory-page/StoreInventoryItem.tsx
Labels: Changelog-Missing

#8462 prevent dim from automatically filling the 50th consumables slot
  src/app/farming/actions.ts
  src/app/inventory/item-move-service.ts
  src/app/inventory/move-item.ts
  src/app/loadout-drawer/loadout-apply.ts
  src/app/loadout-drawer/postmaster.ts
Labels: Changelog-Missing

#8468 Move user guide links back to GitHub
  .github/ISSUE_TEMPLATE/bug_report.yml
  docs/OLD_CHANGELOG/OLD_CHANGELOG_6.X.X.md
  src/app/dim-ui/UserGuideLink.tsx
  src/app/loadout-builder/LoadoutBuilder.tsx
  src/app/loadout/loadout-share/LoadoutShareSheet.tsx
  src/app/login/Login.tsx
  src/app/search/SearchBar.tsx
  src/app/shell/About.tsx
  src/app/shell/ErrorPanel.tsx
  src/app/shell/Header.tsx
  src/index.html
Labels: Changelog-Missing

#8473 Fix sidecar positioning
  src/app/item-popup/sidecar-popper-modifier.ts
Labels: Changelog-Missing

#8474 Lint to prevent accidental use of global window properties
  .eslintrc
  src/app/utils/exceptions.ts
Labels: Changelog-Missing

#8470 Remove inital load of stripped-down components
  src/app/bungie-api/destiny2-api.ts
  src/app/inventory-page/Inventory.tsx
  src/app/inventory/d2-stores.ts
  src/app/inventory/store/hooks.ts
Labels: Changelog-Missing

#8472 Use a selector to get an item sort function
  src/app/inventory-page/StoreBucket.tsx
  src/app/item-picker/ItemPicker.tsx
  src/app/search/SearchResults.tsx
  src/app/settings/item-sort.ts
  src/app/shell/item-comparators.ts
Labels: Changelog-Missing

#8480 Fix changelog - PR #8465 was not included in the 7.21.0 release.
  docs/CHANGELOG.md
Labels: Changelog-Applied

#8479 Filter out enhanced intrinsics from Organizer perk columns
  docs/CHANGELOG.md
  src/app/organizer/Columns.tsx
Labels: Changelog-Applied

#8478 Item element DOM/style simplification
  src/app/inventory/BadgeInfo.m.scss
  src/app/inventory/BadgeInfo.m.scss.d.ts
  src/app/inventory/BadgeInfo.tsx
  src/app/inventory/ConnectedInventoryItem.tsx
  src/app/inventory/InventoryItem.tsx
  src/app/inventory/ItemIcon.m.scss
  src/app/inventory/ItemIcon.tsx
  src/app/inventory/RatingIcon.m.scss
Labels: Changelog-Missing

#8485 Fix showing wishlist matches on vendor rolls
  docs/CHANGELOG.md
  src/app/wishlists/selectors.ts
  src/app/wishlists/wishlists.ts
Labels: Changelog-Applied

#8486 Reload Clarity descriptions along with store refreshes every hour
  src/app/clarity/descriptions/loadDescriptions.ts
  src/app/inventory/d2-stores.ts
Labels: Changelog-Missing

#8489 Upgrades
  package.json
  src/app/whats-new/WhatsNew.tsx
  yarn.lock
Labels: Changelog-Missing

#8492 Fix icon watermark scaling at reduced item sizes
  src/app/inventory/ItemIcon.tsx
Labels: Changelog-None, Changelog-Missing

#8493 fix vendor location displays
  src/app/vendors/d2-vendors.ts
Labels: Changelog-Missing

#8487 Add descriptions for deepsight keywords
  config/i18n.json
  src/locale/en.json
Labels: Changelog-Missing

#8497 i18next-scanner upgrades
  i18next-scanner.config.js
  package.json
  src/app/accounts/destiny-account.ts
  src/app/destiny1/activities/Activities.tsx
  src/app/inventory-page/CategoryStrip.tsx
  src/app/inventory-page/DesktopStores.tsx
  src/app/inventory/dim-item-info.ts
  src/app/item-popup/SocketDetailsSelectedPlug.tsx
  src/app/loadout-builder/filter/TierSelect.tsx
  src/app/loadout/loadout-edit/LoadoutEdit.tsx
  src/app/loadout/loadout-ui/LoadoutItemCategorySection.tsx
  src/app/progress/Pursuits.tsx
  src/app/store-stats/D1CharacterStats.tsx
  src/app/utils/time.ts
  src/browsercheck.js
  yarn.lock
Labels: Changelog-None, Changelog-Missing

#8499 Fix vendor refresh dates
  config/i18n.json
  src/app/vendors/SingleVendor.tsx
  src/app/vendors/Vendor.tsx
  src/locale/en.json
Labels: Changelog-Missing

#8500 get xur location from bungie
  config/content-security-policy.js
  package.json
  src/app/vendors/Vendor.tsx
  src/app/vendors/actions.ts
  src/app/vendors/reducer.ts
  yarn.lock
Labels: Changelog-Missing

#8502 compact some weapon pattern UI in item popup
  config/i18n.json
  src/app/dim-ui/WeaponDeepsightInfo.m.scss
  src/app/dim-ui/WeaponDeepsightInfo.m.scss.d.ts
  src/app/dim-ui/WeaponDeepsightInfo.tsx
  src/locale/en.json
Labels: Changelog-Missing

#8503 Fix spacing for RichDestinyText
  src/app/dim-ui/RichDestinyText.m.scss
  src/app/dim-ui/RichDestinyText.m.scss.d.ts
  src/app/dim-ui/RichDestinyText.tsx
Labels: Changelog-Missing

#8504 More consistently use the correct valueStyle, and show a single decimal place where appropriate
  docs/CHANGELOG.md
  src/app/dim-ui/WeaponCraftedInfo.tsx
  src/app/inventory/store/objectives.ts
  src/app/progress/Objective.tsx
  src/app/progress/Pursuit.tsx
  src/app/progress/PursuitItem.tsx
  src/app/records/Record.tsx
  src/app/shell/formatters.ts
Labels: Changelog-Applied

#8513 Upgrades
  package.json
  yarn.lock
Labels: Changelog-Missing

#8509 Fix iOS performance by lazy-loading tile images
  src/app/dim-ui/ElementIcon.m.scss
  src/app/dim-ui/ElementIcon.tsx
  src/app/inventory/BadgeInfo.tsx
  src/app/inventory/InventoryItem.m.scss
  src/app/inventory/InventoryItem.m.scss.d.ts
  src/app/inventory/InventoryItem.tsx
  src/app/inventory/ItemIcon.m.scss
  src/app/inventory/ItemIcon.tsx
  src/app/inventory/ItemIconPlaceholder.m.scss
  src/app/inventory/ItemIconPlaceholder.m.scss.d.ts
  src/app/inventory/ItemIconPlaceholder.tsx
Labels: Changelog-Missing

#8515 Drive fa-subset from our actual list of icons
  .github/workflows/deploy-beta.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/i18n-bot-download.yml
  .github/workflows/i18n-update.yml
  .github/workflows/pr-build.yml
  .github/workflows/pr-test-and-lint.yml
  jest.config.js
  src/app/shell/icons/Library.mjs
  src/app/shell/icons/Library.ts
  src/app/shell/icons/custom/index.ts
  src/app/shell/icons/index.ts
  src/data/webfonts/fa-brands-400.eot
  src/data/webfonts/fa-brands-400.svg
  src/data/webfonts/fa-brands-400.ttf
  src/data/webfonts/fa-brands-400.woff
  src/data/webfonts/fa-brands-400.woff2
  src/data/webfonts/fa-regular-400.eot
  src/data/webfonts/fa-regular-400.svg
  src/data/webfonts/fa-regular-400.ttf
  src/data/webfonts/fa-regular-400.woff
  src/data/webfonts/fa-regular-400.woff2
  src/data/webfonts/fa-solid-900.eot
  src/data/webfonts/fa-solid-900.svg
  src/data/webfonts/fa-solid-900.ttf
  src/data/webfonts/fa-solid-900.woff
  src/data/webfonts/fa-solid-900.woff2
  src/fa-subset.mjs
Labels: Changelog-Missing

#8514 Slightly reduce the size of the window where the header links disappear
  src/app/shell/Header.m.scss
Labels: Changelog-Missing

#8518 Rename activity tracker
  src/app/App.tsx
  src/app/dim-ui/AutoRefresh.tsx
Labels: Changelog-Missing

#8523 Auto refresh, but only when the player is playing
  config/i18n.json
  src/app/bungie-api/destiny2-api.ts
  src/app/dim-ui/AutoRefresh.tsx
  src/app/inventory/selectors.ts
  src/app/shell/RefreshButton.m.scss
  src/app/shell/RefreshButton.m.scss.d.ts
  src/app/shell/RefreshButton.tsx
  src/locale/en.json
Labels: Changelog-Missing

#8517 Make everything reactive on the manifest
  package.json
  src/app/armory/crafting-utils.ts
  src/app/destiny2/d2-definitions.ts
  src/app/dim-ui/RichDestinyText.tsx
  src/app/dim-ui/rich-destiny-text.ts
  src/app/inventory/store/d2-item-factory.ts
  src/app/inventory/store/patterns.ts
  src/app/search/search-filters/freeform.tsx
  yarn.lock
Labels: Changelog-Missing

#8511 Tidy up plug descriptions
  docs/CHANGELOG.md
  src/app/_variables.scss
  src/app/clarity/descriptions/ClarityDescriptions.tsx
  src/app/clarity/descriptions/Description.m.scss
  src/app/clarity/descriptions/Description.m.scss.d.ts
  src/app/clarity/descriptions/descriptionInterface.ts
  src/app/clarity/selectors.ts
  src/app/dim-ui/RichDestinyText.tsx
  src/app/inventory/store/masterwork.ts
  src/app/inventory/store/stats.ts
  src/app/item-popup/ItemSocketsGeneral.m.scss
  src/app/item-popup/ItemSocketsGeneral.m.scss.d.ts
  src/app/item-popup/ItemSocketsGeneral.tsx
  src/app/item-popup/ItemStat.tsx
  src/app/item-popup/PlugTooltip.m.scss
  src/app/item-popup/PlugTooltip.m.scss.d.ts
  src/app/item-popup/PlugTooltip.tsx
  src/app/item-popup/SocketDetailsSelectedPlug.m.scss
  src/app/item-popup/SocketDetailsSelectedPlug.m.scss.d.ts
  src/app/item-popup/SocketDetailsSelectedPlug.tsx
  src/app/item-triage/triage-factors.tsx
  src/app/loadout-drawer/loadout-utils.ts
  src/app/loadout/plug-drawer/SelectablePlug.tsx
  src/app/search/d2-known-values.ts
  src/app/utils/item-utils.ts
  src/app/utils/plug-descriptions.ts
  src/app/utils/socket-utils.ts
Labels: Changelog-Applied

#8529 Use cut-down version of Fontawesome fonts
  config/webpack.js
  src/app/shell/icons/AppIcon.scss
  src/app/shell/icons/AppIcon.tsx
Labels: Changelog-Missing
