Repository DestinyItemManager/DIM, pull requests merged in 2022-01, with the labels that each got.

#7617 Loadout stats
  src/app/loadout/LoadoutView.m.scss
  src/app/loadout/loadout-ui/LoadoutItemCategorySection.tsx
Labels: no changelog

#7619 Fix loadouts showing subclass in the "general" category
  src/app/loadout/LoadoutView.tsx
Labels: no changelog

#7614 Remove unnecessary wrapper divs from plugs
  src/app/loadout/LoadoutView.tsx
  src/app/loadout/loadout-ui/PlugDef.tsx
  src/app/progress/TrackedTriumphs.tsx
Labels: no changelog

#7616 Disable immer auto-freeze to fix that issue trying to update frozen stats
  src/app/loadout-drawer/loadout-apply-state.ts
Labels: no changelog

#7608 Fix localization for AWA bug
  config/i18n.json
  src/app/inventory/advanced-write-actions.ts
  src/locale/dim.json
Labels: no changelog

#7610 Only prevent text selection on mobile
  src/app/main.scss
Labels: no changelog

#7621 Plumb through cancelToken so loadouts can be properly canceled
  src/app/loadout-drawer/loadout-apply.ts
Labels: no changelog

#7611 Clean up SocketDetails UI, let us choose whether to insert plug on accept
  src/app/item-picker/ItemPicker.tsx
  src/app/item-popup/ItemSocketsGeneral.tsx
  src/app/item-popup/ItemSocketsWeapons.tsx
  src/app/item-popup/SocketDetails.tsx
  src/app/item-popup/SocketDetailsSelectedPlug.m.scss
  src/app/item-popup/SocketDetailsSelectedPlug.m.scss.d.ts
  src/app/item-popup/SocketDetailsSelectedPlug.tsx
Labels: no changelog

#7613 Force disabled buttons to have no selection/hover highlight
  src/app/main.scss
Labels: no changelog

#7604 Bootstrap of loadout drawer v2.
  config/webpack.js
  src/app/loadout-drawer/LoadoutDrawer2.tsx
  src/app/loadout-drawer/LoadoutDrawerOptions.m.scss
  src/app/loadout-drawer/LoadoutDrawerOptions.m.scss.d.ts
  src/app/loadout-drawer/LoadoutDrawerOptions.tsx
  src/app/loadout-drawer/loadout-drawer.scss
  src/app/shell/Destiny.tsx
  src/global.d.ts
Labels: no changelog

#7612 Clean up mod assignment structures
  src/app/loadout-builder/generated-sets/GeneratedSet.tsx
  src/app/loadout/mod-assignment-drawer/ModAssignmentDrawer.tsx
  src/app/loadout/mod-assignment-utils.ts
Labels: no changelog

#7626 Fix missing socket overrides in loadout page display.
  src/app/loadout/LoadoutView.tsx
Labels: no changelog

#7628 Change rate limit for socketing free mods.
  src/app/bungie-api/rate-limit-config.ts
Labels: no changelog

#7629 Fix perf issues with loadout apply
  src/app/bungie-api/rate-limit-config.ts
  src/app/inventory/store/sockets.ts
  src/app/loadout-drawer/loadout-apply-state.ts
  src/app/loadout-drawer/loadout-apply.ts
Labels: no changelog

#7615 Simplify fillLoadoutFromEquipped
  src/app/loadout-drawer/LoadoutDrawer.tsx
  src/app/loadout-drawer/LoadoutDrawerContents.tsx
Labels: no changelog

#7624 Mobile style fixes
  docs/CHANGELOG.md
  src/app/organizer/ItemTable.m.scss
  src/app/shell/Header.m.scss
Labels: Mobile Interface

#7625 Hide show mod placements button on equipped loadout.
  src/app/loadout/LoadoutView.tsx
  src/app/loadout/Loadouts.tsx
Labels: no changelog

#7623 Keep track of required vs optional plug instructions for better reporting
  src/app/loadout-drawer/loadout-apply.ts
  src/app/loadout-drawer/loadout-types.ts
  src/app/loadout/mod-assignment-utils.ts
Labels: no changelog

#7631 Turn auto freeze back off
  src/app/loadout-drawer/loadout-apply-state.ts
Labels: no changelog

#7635 Revert "Turn auto freeze back off"
  src/app/loadout-drawer/loadout-apply-state.ts
Labels: no changelog

#7638 Use DefItemIcon in move notification.
  src/app/inventory/MoveNotifications.tsx
Labels: no changelog

#7637 Fix empty modslots becoming required
  src/app/loadout-drawer/loadout-apply.ts
  src/app/loadout-drawer/loadout-types.ts
  src/app/loadout/mod-assignment-utils.ts
Labels: no changelog

#7639 Better updates for DimPlug's.
  src/app/inventory/item-types.ts
  src/app/inventory/store/sockets.ts
  src/app/inventory/store/stats.ts
Labels: no changelog

#7647 Revert changes to loadout apply state regarding immer.
  src/app/inventory/store/sockets.ts
  src/app/loadout-drawer/loadout-apply-state.ts
  src/app/loadout-drawer/loadout-apply.ts
Labels: no changelog

#7649 Revert #7639 ryan-immutable-dim-plugs
  src/app/inventory/item-types.ts
  src/app/inventory/store/sockets.ts
  src/app/inventory/store/stats.ts
Labels: no changelog

#7640 Reduce a bit of extra render in SearchBar
  src/app/search/SearchFilter.tsx
  src/app/shell/reducer.ts
Labels: no changelog

#7644 Update Loadout lastUpdatedAt when saving
  src/app/dim-api/reducer.ts
Labels: no changelog

#7641 Throttle loadout updates
  src/app/inventory/MoveNotifications.tsx
  src/app/utils/hooks.ts
Labels: no changelog

#7596 Store header on Android UI issue with positioning when tray open
  src/app/dim-ui/Sheet.tsx
  src/app/inventory/HeaderShadowDiv.m.scss
  src/app/inventory/Stores.scss
Labels: no changelog

#7651 Freeze empties to prevent accidental mutation
  src/app/utils/empty.ts
Labels: no changelog

#7650 Immutable DimPlugs take two.
  src/app/inventory/item-types.ts
  src/app/inventory/store/sockets.ts
  src/app/inventory/store/stats.ts
Labels: no changelog

#7583 Save ability defaults as socket overrides.
  src/app/loadout-builder/LoadoutBuilder.tsx
  src/app/loadout-drawer/LoadoutDrawer.tsx
  src/app/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/loadout-drawer/loadout-drawer-reducer.ts
  src/app/loadout-drawer/loadout-utils.ts
Labels: no changelog

#7658 Cleanup socket overrides from equipped.
  src/app/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/loadout-drawer/loadout-utils.ts
Labels: no changelog

#7665 Fix React error when sorting transmog bounties
  src/app/search/d2-known-values.ts
  src/app/vendors/VendorItems.tsx
  src/app/vendors/d2-vendors.ts
  src/app/vendors/vendor-item.ts
Labels: no changelog

#7653 Apply the default ornament
  config/i18n.json
  src/app/inventory/advanced-write-actions.ts
  src/locale/dim.json
Labels: no changelog

#7668 Resolve issue with character header not scrolling
  src/app/dim-ui/Sheet.tsx
  src/app/inventory/HeaderShadowDiv.m.scss
  src/app/inventory/Stores.scss
Labels: no changelog

#7600 Fashion Loadouts
  config/i18n.json
  docs/CHANGELOG.md
  src/app/inventory/selectors.ts
  src/app/loadout-builder/item-filter.ts
  src/app/loadout-builder/loadout-builder-reducer.ts
  src/app/loadout-builder/process/useProcess.ts
  src/app/loadout-drawer/LoadoutDrawer.tsx
  src/app/loadout-drawer/LoadoutDrawer2.tsx
  src/app/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/loadout-drawer/LoadoutDrawerOptions.tsx
  src/app/loadout-drawer/loadout-apply.ts
  src/app/loadout-drawer/loadout-drawer-reducer.ts
  src/app/loadout-drawer/loadout-utils.ts
  src/app/loadout-drawer/subclass-drawer/ItemSocketsSubclass.tsx
  src/app/loadout/LoadoutView.m.scss
  src/app/loadout/LoadoutView.m.scss.d.ts
  src/app/loadout/LoadoutView.tsx
  src/app/loadout/fashion/FashionDrawer.m.scss
  src/app/loadout/fashion/FashionDrawer.m.scss.d.ts
  src/app/loadout/fashion/FashionDrawer.tsx
  src/app/loadout/loadout-ui/BucketPlaceholder.m.scss
  src/app/loadout/loadout-ui/BucketPlaceholder.m.scss.d.ts
  src/app/loadout/loadout-ui/BucketPlaceholder.tsx
  src/app/loadout/loadout-ui/LoadoutItemCategorySection.m.scss
  src/app/loadout/loadout-ui/LoadoutItemCategorySection.m.scss.d.ts
  src/app/loadout/loadout-ui/LoadoutItemCategorySection.tsx
  src/app/loadout/loadout-ui/LoadoutParametersDisplay.m.scss
  src/app/loadout/loadout-ui/LoadoutParametersDisplay.m.scss.d.ts
  src/app/loadout/loadout-ui/LoadoutParametersDisplay.tsx
  src/app/loadout/loadout-ui/Sockets.tsx
  src/app/loadout/mod-assignment-utils.ts
  src/app/loadout/mod-utils.ts
  src/app/organizer/item-category-icons.ts
  src/app/utils/socket-utils.ts
  src/locale/dim.json
Labels: Feature: Loadouts

#7685 LO: Clear subclass when switching characters
  src/app/loadout-builder/loadout-builder-reducer.ts
Labels: no changelog

#7674 Move Ada and Banshee up in the Vendors view
  src/app/vendors/d2-vendors.ts
Labels: no changelog

#7679 Handle case where characterId is not specified
  src/app/inventory/selectors.ts
  src/app/loadout-drawer/loadout-apply.ts
Labels: no changelog

#7681 Fashion followups, part 1
  config/i18n.json
  src/app/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/loadout-drawer/loadout-apply.ts
  src/app/loadout/fashion/FashionDrawer.tsx
  src/app/loadout/loadout-ui/LoadoutItemCategorySection.tsx
  src/locale/dim.json
Labels: no changelog

#7680 Remove misspelled D1 search aliases
  cspell-dim-dict.txt
  src/app/search/search-filters/d1-filters.tsx
Labels: no changelog

#7634 Add a little helper that makes createSelector easier to use with useSelector
  src/app/utils/redux-utils.ts
  src/app/vendors/SingleVendor.tsx
  src/app/vendors/Vendors.tsx
  src/app/vendors/selectors.ts
Labels: no changelog

#7701 Remove tooltip from "no preference" slots
  config/i18n.json
  src/app/loadout/fashion/FashionDrawer.tsx
  src/app/main.scss
  src/locale/dim.json
Labels: no changelog

#7690 Reword "select" to "preview"
  config/i18n.json
  src/locale/dim.json
Labels: no changelog

#7507 allow DIM to launch separately
  config/i18n.json
  src/app/shell/Header.m.scss
  src/app/shell/Header.m.scss.d.ts
  src/app/shell/Header.tsx
  src/locale/dim.json
Labels: no changelog

#7710 add settings button to export profile response
  config/i18n.json
  src/app/settings/SettingsPage.tsx
  src/locale/dim.json
Labels: no changelog

#7691 Error handling for apply perk button
  src/app/item-popup/ApplyPerkSelection.tsx
Labels: no changelog

#7682 Refactor loadout builder to preserve LO params
  src/app/loadout-builder/LoadoutBuilder.tsx
  src/app/loadout-builder/loadout-builder-reducer.ts
  src/app/loadout-builder/loadout-params.ts
Labels: no changelog

#7712 Skip attempting to apply fashion mods that can't be assigned to their item
  src/app/loadout-drawer/loadout-apply.ts
  src/app/loadout/fashion/FashionDrawer.tsx
  src/app/loadout/mod-assignment-utils.ts
  src/app/utils/socket-utils.ts
Labels: no changelog

#7714 Set a maximum length for loadout notes
  src/app/loadout-drawer/LoadoutDrawer.tsx
Labels: no changelog

#7717 Improve Records/Collections performance
  src/app/records/PresentationNodeRoot.tsx
Labels: no changelog

#7728 Navigate
  src/app/item-popup/ItemDetails.tsx
  src/app/shell/AccountRedirectRoute.tsx
  src/app/shell/Destiny.tsx
Labels: no changelog

#7729 Remove babel plugins that come with preset-env
  babel.config.js
  package.json
  yarn.lock
Labels: no changelog

#7718 Vendor item compare
  config/i18n.json
  src/app/compare/Compare.tsx
  src/app/compare/CompareItem.m.scss
  src/app/compare/CompareItem.m.scss.d.ts
  src/app/compare/CompareItem.tsx
  src/app/compare/reducer.ts
  src/app/compare/selectors.ts
  src/app/shell/icons/Library.ts
  src/app/vendors/selectors.ts
  src/app/vendors/vendor-item.ts
  src/locale/dim.json
Labels: no changelog

#7735 spelling
  cspell-dim-dict.txt
  src/app/inventory/MoveNotifications.tsx
  src/app/vendors/vendor-item.ts
Labels: no changelog

#7741 i18n fixes
  config/i18n.json
  src/app/compare/CompareItem.tsx
  src/app/progress/ItemFeed.tsx
  src/locale/dim.json
Labels: no changelog

#7739 zh detection fix
  src/browsercheck.js
Labels: no changelog

#7747 Fix kinetic slot icon in gear power tooltip and drawer
  src/app/dim-ui/svgs/BucketIcon.tsx
Labels: no changelog

#7751 Don't show internal error when clicking on sub-vendor without items
  config/i18n.json
  src/app/vendors/VendorItems.tsx
  src/app/vendors/d2-vendors.ts
  src/locale/dim.json
Labels: no changelog

#7752 Update preconnect list
  src/index.html
Labels: no changelog

#7763 Remove orientation prop
  src/manifest-webapp-6-2018.json
Labels: no changelog

#7760 Add style lint for comment spacing
  .eslintrc
  src/app/bungie-api/bungie-service-helper.ts
  src/app/farming/actions.ts
  src/app/loadout-builder/process-worker/stats-set.ts
  src/app/search/SearchBar.tsx
  src/app/shell/Header.tsx
Labels: no changelog

#7764 Test whether removing scale from search-hidden items alleviates slow sheet
  src/app/inventory/InventoryItem.m.scss
Labels: no changelog

#7765 Fix Loadout Optimizer not re-measuring set height when needed
  src/app/loadout-builder/generated-sets/GeneratedSets.tsx
Labels: no changelog

#7761 Mock inventory
  src/app/inventory/actions.ts
  src/app/inventory/d2-stores.ts
  src/app/inventory/reducer.ts
  src/app/settings/SettingsPage.tsx
  src/app/settings/Troubleshooting.tsx
Labels: no changelog

#7766 Fix LO layout error from #7765
  src/app/loadout-builder/generated-sets/GeneratedSets.tsx
Labels: no changelog

#7768 Allow popups to spill out of a sheet.
  src/app/dim-ui/Sheet.scss
Labels: no changelog

#7756 prevent exotics from ruining the grading curve for "max" filters
  src/app/search/search-filters/stats.tsx
Labels: no changelog

#7774 Don't freeze initial height in socket drawer
  src/app/item-popup/SocketDetails.m.scss
  src/app/item-popup/SocketDetails.tsx
Labels: no changelog

#7753 Apply hadErrors fix from D2 to D1
  src/app/inventory/store/d1-item-factory.ts
Labels: no changelog

#7779 fix danger buttons & establish global line height
  src/app/loadout-drawer/LoadoutDrawerOptions.tsx
  src/app/loadout/Loadouts.tsx
  src/app/main.scss
Labels: no changelog

#7781 Various types improvements
  src/app/dim-ui/Switch.tsx
  src/app/inventory/StoreBucket.tsx
  src/app/inventory/store/d1-item-factory.ts
  src/app/item-picker/ItemPicker.tsx
  src/app/item-popup/SocketDetails.tsx
  src/app/loadout-drawer/LoadoutPopup.tsx
  src/app/loadout/ModPicker.tsx
  src/app/loadout/mod-permutations.ts
  src/app/manifest/reducer.ts
  src/app/search/autocomplete.test.ts
  src/app/search/filter-types.ts
  src/app/search/search-utils.test.ts
  src/app/settings/Checkbox.tsx
  src/app/storage/LocalStorageInfo.tsx
Labels: no changelog

#7785 Stop reporting hash lookup failures to Sentry
  src/app/destiny2/d2-definitions.ts
  src/app/utils/log.ts
Labels: no changelog

#7784 Lower CF cache time for HTML
  src/htaccess
Labels: no changelog

#7786 Try deleting the IDB database to fix it
  config/webpack.js
  package.json
  src/Index.tsx
  src/StorageTest.tsx
  src/app/App.tsx
  src/app/accounts/observers.ts
  src/app/accounts/platforms.ts
  src/app/destiny1/vendors/vendor.service.ts
  src/app/dim-api/actions.ts
  src/app/inventory/actions.ts
  src/app/inventory/advanced-write-actions.ts
  src/app/inventory/observers.ts
  src/app/manifest/d1-manifest-service.ts
  src/app/manifest/manifest-service-json.ts
  src/app/storage/idb-keyval.ts
  src/app/wishlists/observers.ts
  src/app/wishlists/wishlist-fetch.ts
  yarn.lock
Labels: no changelog

#7782 LO Energy Choice styling
  src/app/loadout-builder/filter/EnergyOptions.m.scss
  src/app/loadout-builder/filter/EnergyOptions.tsx
  src/app/main.scss
Labels: no changelog

#7789 Fix interpretation of insertPlugFreeProtectedPlugItemHashes
  src/app/inventory/advanced-write-actions.ts
  src/app/inventory/store/override-sockets.ts
Labels: no changelog

#7794 Fix Fashion Loadouts erroneously reporting some shaders as unavailable
  src/app/loadout/LoadoutView.tsx
  src/app/loadout/fashion/FashionDrawer.tsx
  src/app/loadout/loadout-ui/LoadoutItemCategorySection.tsx
  src/app/utils/socket-utils.ts
Labels: no changelog

#7787 Adjust explanation of single character mode.
  config/i18n.json
  src/locale/dim.json
Labels: no changelog

#7804 Upgrades
  package.json
  yarn.lock
Labels: no changelog

#7807 Fix CheckButton style
  src/app/dim-ui/CheckButton.m.scss
  src/app/progress/ItemFeed.m.scss
  src/app/records/PlugSet.tsx
  src/app/records/Records.m.scss
  src/app/records/Records.m.scss.d.ts
  src/app/records/Records.tsx
  src/app/records/collections.scss
Labels: no changelog
