Repository DestinyItemManager/DIM, pull requests merged in 2022-02, with the labels that each got.

#7805 Define DefaultRootState type for react-redux
  package.json
  src/app/store/types.ts
  src/app/vendors/SingleVendor.tsx
  yarn.lock
Labels: no changelog

#7806 Bucket type to bucket hash
  src/app/destiny1/d1-buckets.ts
  src/app/destiny1/loadout-builder/ExcludeItemsDropTarget.tsx
  src/app/destiny1/loadout-builder/LoadoutBuilderDropTarget.tsx
  src/app/destiny1/loadout-builder/LoadoutBuilderLockPerk.tsx
  src/app/destiny1/loadout-builder/utils.ts
  src/app/destiny2/d2-buckets.ts
  src/app/dim-ui/svgs/BucketIcon.tsx
  src/app/farming/actions.ts
  src/app/gear-power/GearPower.tsx
  src/app/infuse/InfusionFinder.tsx
  src/app/inventory/DraggableInventoryItem.tsx
  src/app/inventory/InventoryItem.tsx
  src/app/inventory/StoreBucketDropTarget.tsx
  src/app/inventory/StoreBuckets.tsx
  src/app/inventory/d2-stores.ts
  src/app/inventory/item-move-service.ts
  src/app/inventory/reducer.ts
  src/app/inventory/selectors.ts
  src/app/inventory/store/d1-item-factory.ts
  src/app/inventory/store/stats.ts
  src/app/inventory/stores-helpers.ts
  src/app/item-actions/ActionButtons.tsx
  src/app/item-actions/LockButton.tsx
  src/app/item-picker/ItemPicker.tsx
  src/app/item-popup/ItemPopupHeader.tsx
  src/app/item-popup/item-popup-actions.ts
  src/app/item-triage/ItemTriage.tsx
  src/app/loadout-builder/process-worker/types.ts
  src/app/loadout-builder/process/mappers.ts
  src/app/loadout-drawer/GeneratedLoadoutStats.tsx
  src/app/loadout-drawer/LoadoutDrawerBucket.tsx
  src/app/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/loadout-drawer/LoadoutDrawerDropTarget.tsx
  src/app/loadout-drawer/LoadoutDrawerItem.tsx
  src/app/loadout-drawer/auto-loadouts.ts
  src/app/loadout-drawer/loadout-apply.ts
  src/app/loadout-drawer/loadout-drawer-reducer.ts
  src/app/loadout-drawer/loadout-utils.ts
  src/app/loadout-drawer/postmaster.ts
  src/app/loadout/item-utils.ts
  src/app/search/d1-known-values.ts
  src/app/search/search-filter-values.ts
  src/app/search/search-filters/known-values.tsx
  src/app/search/search-filters/simple.tsx
  src/app/shell/filters.ts
  src/app/utils/item-utils.ts
Labels: no changelog

#7810 Give vendors checkbutton some space
  src/app/dim-ui/CheckButton.m.scss
  src/app/vendors/Vendors.m.scss
  src/app/vendors/Vendors.m.scss.d.ts
  src/app/vendors/Vendors.tsx
Labels: no changelog

#7812 Show wish list info and clear button for file-loaded wishlists too
  src/app/settings/WishListSettings.tsx
Labels: no changelog

#7811 Add Kinetic Fusion and Energy Linear categories to Organizer to account for Bastion and Lorentz
  src/app/organizer/ItemTypeSelector.tsx
Labels: no changelog

#7820 Ensure organizer icons in the selected category retain their inverted color after moving mouse out
  src/app/organizer/ItemTypeSelector.m.scss
Labels: no changelog

#7827 Remove builtin margin from CheckButton
  src/app/dim-ui/CheckButton.m.scss
  src/app/records/Records.m.scss
Labels: no changelog

#7828 Allow changing the placement of dropdowns
  src/app/dim-ui/Dropdown.tsx
Labels: no changelog

#7835 Organizer: fix recoil base stat display
  src/app/organizer/Columns.tsx
  src/app/organizer/ItemTable.m.scss
  src/app/organizer/ItemTable.m.scss.d.ts
Labels: no changelog

#7833 Explicitly list possible filter syntaxes in filter definition
  src/app/search/FilterHelp.tsx
  src/app/search/__snapshots__/search-utils.test.ts.snap
  src/app/search/filter-types.ts
  src/app/search/search-filters/loadouts.tsx
  src/app/search/search-filters/range-numeric.tsx
  src/app/search/search-filters/range-overload.tsx
  src/app/search/search-filters/stats.tsx
  src/app/search/search-utils.test.ts
  src/app/search/suggestions-generation.ts
Labels: no changelog

#7836 clean up optimizer upgrade description strings
  config/i18n.json
  src/locale/dim.json
Labels: no changelog

#7840 Fix Assume Masterwork: None not upgrading items to 7 energy in set rendering
  src/app/loadout/mod-assignment-utils.ts
Labels: no changelog

#7844 i18n update workflow
  .github/workflows/i18n-update.yml
Labels: no changelog

#7847 Fix autocompletion considering rangeoverload filters complete too early
  src/app/search/__snapshots__/autocomplete.test.ts.snap
  src/app/search/autocomplete.test.ts
  src/app/search/autocomplete.ts
Labels: no changelog

#7846 Build/deploy improvements
  .github/workflows/deploy-beta.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/pr-build.yml
  Gruntfile.js
  brotli/brotli
  build/deploy-prod.sh
  build/rsync-deploy.sh
  config/webpack.js
  package.json
  yarn.lock
Labels: no changelog

#7845 Break instead of continue
  src/app/loadout/mod-assignment-utils.ts
Labels: no changelog

#7855 fix prod deploy
  .github/workflows/deploy-prod.yml
Labels: no changelog

#7854 setup-node@v2
  .github/workflows/deploy-beta.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/i18n-bot-download.yml
  .github/workflows/pr-build.yml
Labels: no changelog

#7857 More deploy improvements
  .github/workflows/deploy-prod.yml
  build/deploy-prod.sh
  build/rsync-deploy.sh
  config/webpack.js
Labels: no changelog

#7860 Remove voca
  cspell-dim-dict.txt
  package.json
  src/app/search/search-filters/freeform.tsx
  src/global.d.ts
  yarn.lock
Labels: no changelog

#7862 LO: Unpin item in bucket of newly excluded item
  src/app/loadout-builder/loadout-builder-reducer.ts
Labels: no changelog

#7872 eslint cache-strategy content
  .github/workflows/pr-build.yml
  build/set-mtime-to-md5.sh
  package.json
Labels: Infrastructure: Build, no changelog

#7873 Upgrades
  package.json
  src/app/inventory/DraggableInventoryItem.tsx
  src/app/organizer/ItemTable.tsx
  src/app/settings/Spreadsheets.tsx
  src/app/settings/Troubleshooting.tsx
  src/app/storage/ImportExport.tsx
  yarn.lock
Labels: no changelog

#7881 onClearLoadoutParameters
  src/app/loadout/loadout-edit/LoadoutEdit.tsx
  src/app/loadout/loadout-edit/LoadoutEditSection.tsx
Labels: no changelog

#7882 GitHub Actions Concurrency
  .github/workflows/deploy-beta.yml
  .github/workflows/pr-build.yml
Labels: Infrastructure: Build, no changelog

#7889 Use correct store ID for new loadout drawer's mod picker
  src/app/loadout-drawer/LoadoutDrawer.tsx
  src/app/loadout-drawer/LoadoutDrawerOptions.tsx
  src/app/loadout/loadout-ui/LoadoutMods.tsx
  src/app/loadout/mod-assignment-drawer/ModAssignmentDrawer.tsx
Labels: no changelog

#7874 Remove dead code and unused exports
  package.json
  src/app/armory/Links.tsx
  src/app/bungie-api/destiny1-api.ts
  src/app/destiny1/d1-factions.ts
  src/app/dim-api/actions.ts
  src/app/dim-ui/ClassIcon.tsx
  src/app/dim-ui/Sheet.tsx
  src/app/dim-ui/SpecialtyModSlotIcon.tsx
  src/app/dim-ui/svgs/BucketIcon.tsx
  src/app/dim-ui/svgs/itemCategory.ts
  src/app/farming/actions.ts
  src/app/inventory/ItemIcon.tsx
  src/app/inventory/advanced-write-actions.ts
  src/app/inventory/store/character-utils.ts
  src/app/inventory/store/sockets.ts
  src/app/item-actions/LockButton.tsx
  src/app/item-popup/RecoilStat.tsx
  src/app/item-popup/SocketDetails.tsx
  src/app/item-triage/ItemTriage.tsx
  src/app/loadout-builder/item-filter.ts
  src/app/loadout-builder/loadout-params.ts
  src/app/loadout-builder/mod-utils.ts
  src/app/loadout-builder/process-worker/process-utils.ts
  src/app/loadout-drawer/LoadoutPopup.tsx
  src/app/loadout-drawer/loadout-type-converters.ts
  src/app/loadout-drawer/postmaster.ts
  src/app/loadout/loadout-edit/LoadoutEditBucket.tsx
  src/app/loadout/loadout-edit/LoadoutEditBucketDropTarget.tsx
  src/app/loadout/mod-assignment-utils.ts
  src/app/progress/Pursuits.tsx
  src/app/progress/SeasonalChallenges.tsx
  src/app/progress/SeasonalRank.tsx
  src/app/progress/selectors.ts
  src/app/records/presentation-nodes.ts
  src/app/search/d2-known-values.ts
  src/app/search/search-filters/dupes.tsx
  src/app/search/search-filters/freeform.tsx
  src/app/settings/Select.tsx
  src/app/shell/filters.ts
  src/app/shell/icons/Library.ts
  src/app/shell/icons/custom/BattleNet.ts
  src/app/shell/icons/custom/Engram.ts
  src/app/shell/icons/custom/Hunter.ts
  src/app/shell/icons/custom/Power.ts
  src/app/shell/icons/custom/PowerAlt.ts
  src/app/shell/icons/custom/Stadia.ts
  src/app/shell/icons/custom/Titan.ts
  src/app/shell/icons/custom/Warlock.ts
  src/app/utils/item-utils.ts
  src/app/utils/socket-utils.ts
  src/app/utils/time.ts
  src/app/vendors/d2-vendors.ts
  src/app/whats-new/versions.ts
  src/app/wishlists/selectors.ts
  yarn.lock
Labels: no changelog

#7868 Separate filter namespaces between `is:` and `key:value` filters
  src/app/search/__snapshots__/search-config.test.ts.snap
  src/app/search/autocomplete.ts
  src/app/search/search-config.test.ts
  src/app/search/search-config.ts
  src/app/search/search-filter.ts
  src/app/search/search-filters/known-values.tsx
  src/app/search/search-utils.ts
Labels: no changelog

#7900 Remove "loadoutDialogOpen"
  src/app/inventory/StoreInventoryItem.tsx
  src/app/inventory/move-item.ts
  src/app/loadout-drawer/LoadoutDrawer.tsx
  src/app/loadout-drawer/LoadoutDrawer2.tsx
Labels: no changelog

#7901 Handle super sockets the same as ability sockets.
  config/i18n.json
  i18next-scanner.config.js
  src/app/item-popup/SocketDetailsSelectedPlug.tsx
  src/app/loadout-builder/filter/LockArmorAndPerks.tsx
  src/app/loadout-builder/loadout-builder-reducer.ts
  src/app/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/loadout-drawer/loadout-apply.ts
  src/app/loadout-drawer/loadout-utils.ts
  src/app/loadout/SubclassPlugDrawer.tsx
  src/app/utils/socket-utils.ts
  src/locale/dim.json
Labels: no changelog

#7911 Remove clan banners.
  src/app/destiny2/d2-bucket-categories.ts
  src/app/destiny2/d2-buckets.ts
  src/app/inventory/store/season.ts
  src/app/search/__snapshots__/search-config.test.ts.snap
  src/app/search/search-filter-values.ts
  src/app/search/search-filters/dupes.tsx
Labels: no changelog

#7908 Fix logic in getItemsAndSubclassFromLoadout.
  src/app/loadout/LoadoutView.tsx
Labels: no changelog

#7888 i18n-update updates
  .github/workflows/i18n-update.yml
Labels: Infrastructure: Build, no changelog

#7918 i18n-diff test
  .github/workflows/i18n-bot-upload.yml
Labels: Infrastructure: i18n, no changelog

#7885 Fix Loadout Optimizer considering/suggesting items with insufficient energy
  src/app/loadout-builder/LoadoutBuilder.tsx
  src/app/loadout-builder/item-filter.ts
Labels: no changelog

#7902 Make +Loadout work when the loadout drawer isn't open
  config/i18n.json
  src/app/loadout-drawer/LoadoutDrawer.tsx
  src/app/loadout-drawer/LoadoutDrawer2.tsx
  src/app/loadout-drawer/loadout-drawer-reducer.ts
  src/app/loadout/loadout-edit/LoadoutEdit.tsx
  src/locale/dim.json
Labels: no changelog

#7920 dont build PRs on doc only changes
  .github/workflows/pr-build.yml
Labels: Infrastructure: Build, no changelog

#7922 Remove will-change from Sheet to resolve Edge blurriness
  src/app/dim-ui/Sheet.scss
Labels: no changelog

#7926 Filter loadout to allowed items when saving
  src/app/loadout-drawer/LoadoutDrawer2.tsx
Labels: no changelog

#7928 cspell updates
  .github/workflows/changelog-check.yml
  .github/workflows/check-spelling.yml
  cspell-dim-dict.txt
Labels: no changelog

#7933 Don't remove missing items when saving
  src/app/loadout-drawer/LoadoutDrawer2.tsx
Labels: no changelog

#7931 fix collections armor stats
  src/app/inventory/store/sockets.ts
Labels: no changelog

#7934 Fix floating season tag, remove max height
  src/app/loadout-builder/filter/ExoticArmorChoice.m.scss
Labels: no changelog

#7927 Add plus icons for adding unequipped items to loadouts
  src/app/loadout-drawer/LoadoutDrawer2.tsx
  src/app/loadout/loadout-edit/LoadoutEdit.tsx
  src/app/loadout/loadout-edit/LoadoutEditBucket.m.scss
  src/app/loadout/loadout-edit/LoadoutEditBucket.m.scss.d.ts
  src/app/loadout/loadout-edit/LoadoutEditBucket.tsx
Labels: no changelog

#7950 temporarily filter out some tooltips
  src/app/inventory/store/d2-item-factory.ts
Labels: no changelog

#7952 fix craftables node generation
  src/app/item-popup/item-popup.ts
  src/app/records/Craftable.tsx
  src/app/records/PresentationNodeRoot.tsx
  src/app/records/Records.tsx
  src/app/records/presentation-nodes.ts
Labels: no changelog

#7954 deepsight weapons filter
  config/i18n.json
  docs/CHANGELOG.md
  src/app/search/__snapshots__/search-config.test.ts.snap
  src/app/search/search-filters/sockets.tsx
  src/locale/dim.json
Labels: no changelog

#7965 Void 3.0 subclass fixes
  src/app/inventory/ItemIcon.tsx
  src/app/loadout-builder/loadout-builder-reducer.ts
  src/app/loadout-builder/process/mappers.ts
  src/app/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/loadout-drawer/loadout-utils.ts
  src/app/loadout/SubclassPlugDrawer.tsx
  src/app/loadout/loadout-ui/LoadoutSubclassSection.tsx
  src/app/loadout/mod-assignment-drawer/ModAssignmentDrawer.tsx
  src/app/loadout/mod-assignment-drawer/selectors.ts
  src/app/search/d2-known-values.ts
  src/app/utils/item-utils.ts
Labels: no changelog

#7978 Upgrades
  .eslintrc
  package.json
  src/app/destiny1/loadout-builder/D1LoadoutBuilder.tsx
  src/app/item-picker/ItemPicker.tsx
  src/app/loadout-drawer/subclass-drawer/Subclass.tsx
  src/app/organizer/ItemTable.tsx
  src/app/search/FilterHelp.tsx
  yarn.lock
Labels: no changelog

#7982 Add self to prefetchSrc
  config/content-security-policy.js
Labels: no changelog

#7981 Fix seasonal artifact vendor display
  src/app/vendors/SingleVendor.tsx
Labels: no changelog

#7980 Fix redacted metrics, null tooltips
  src/app/inventory/store/d2-item-factory.ts
  src/app/records/presentation-nodes.ts
Labels: no changelog

#7985 Disable FS Access API for dropzone
  src/app/dim-ui/FileUpload.tsx
  src/app/organizer/ItemTable.tsx
  src/app/settings/Spreadsheets.tsx
Labels: no changelog

#7929 Accept a full loadout from the URL and bring it up in the loadout drawer
  config/i18n.json
  src/app/inventory/item-move-service.ts
  src/app/inventory/store/d1-item-factory.ts
  src/app/inventory/stores-helpers.ts
  src/app/loadout-builder/generated-sets/CompareDrawer.tsx
  src/app/loadout-builder/loadout-builder-reducer.ts
  src/app/loadout-drawer/LoadoutDrawer.tsx
  src/app/loadout-drawer/LoadoutDrawer2.tsx
  src/app/loadout-drawer/LoadoutPopup.tsx
  src/app/loadout-drawer/loadout-apply.ts
  src/app/loadout-drawer/loadout-drawer-reducer.ts
  src/app/loadout-drawer/loadout-item-conversion.ts
  src/app/loadout-drawer/loadout-type-converters.ts
  src/app/loadout-drawer/loadout-utils.ts
  src/app/loadout/LoadoutView.tsx
  src/app/loadout/Loadouts.tsx
  src/app/loadout/loadout-edit/LoadoutEdit.tsx
  src/app/loadout/mod-assignment-drawer/ModAssignmentDrawer.tsx
  src/app/loadout/mod-assignment-drawer/selectors.ts
  src/locale/dim.json
Labels: no changelog
