Repository DestinyItemManager/DIM, pull requests merged in 2022-04, with the labels that each got.

#8212 Query interpretation: Invalid filters are noop instead of true
  src/app/search/search-filter.ts
Labels: no changelog

#8204 Search quotes
  src/app/compare/compare-buttons.tsx
  src/app/inventory/store/sockets.ts
  src/app/item-triage/ItemTriage.tsx
  src/app/organizer/Columns.tsx
  src/app/search/query-parser.test.ts
  src/app/search/query-parser.ts
  src/app/search/search-filters/freeform.tsx
  src/app/search/search-filters/loadouts.tsx
Labels: Feature: Search, no changelog

#8243 Introduce a move session concept, support blind moves in way more cases
  src/app/farming/actions.ts
  src/app/inventory/item-move-service.ts
  src/app/inventory/move-item.ts
  src/app/loadout-drawer/loadout-apply.ts
  src/app/loadout-drawer/postmaster.ts
Labels: no changelog

#8247 Replace reducer with setLoadout
  src/app/destiny1/loadout-drawer/LoadoutDrawer.tsx
  src/app/destiny1/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/destiny1/loadout-drawer/LoadoutDrawerOptions.tsx
  src/app/loadout-drawer/LoadoutDrawer2.tsx
  src/app/loadout-drawer/loadout-drawer-reducer.ts
  src/app/loadout/loadout-edit/LoadoutEdit.tsx
Labels: no changelog

#8262 Make entire popup header clickable, underline on hover
  src/app/item-popup/ItemPopupHeader.m.scss
  src/app/item-popup/ItemPopupHeader.tsx
Labels: no changelog

#8268 Upgrades
  yarn.lock
Labels: no changelog

#8267 More targeted check for overfill
  src/app/inventory/item-move-service.ts
Labels: no changelog

#8274 Hide Black Armory Radiance socket
  src/app/inventory/store/deepsight.ts
  src/app/item-feed/Highlights.tsx
  src/app/item-popup/ItemSocketsWeapons.tsx
  src/app/loadout-builder/filter/ExoticPicker.tsx
  src/app/utils/socket-utils.ts
Labels: no changelog

#8263 Don't attempt to clear unavailable sockets in loadouts
  src/app/loadout/mod-assignment-utils.ts
Labels: no changelog

#8273 Material menu
  src/app/dim-ui/PressTip.m.scss
  src/app/dim-ui/PressTip.m.scss.d.ts
  src/app/dim-ui/PressTip.tsx
  src/app/material-counts/MaterialCounts.m.scss
  src/app/material-counts/MaterialCounts.m.scss.d.ts
  src/app/material-counts/MaterialCounts.tsx
  src/app/material-counts/MaterialCountsWrappers.tsx
  src/app/store-stats/VaultCapacity.tsx
Labels: no changelog

#8272 Move inventory page components into inventory-page
  src/app/destiny1/loadout-drawer/LoadoutDrawer.tsx
  src/app/destiny1/loadout-drawer/LoadoutDrawerBucket.tsx
  src/app/inventory-page/D1Reputation.scss
  src/app/inventory-page/D1Reputation.tsx
  src/app/inventory-page/D1ReputationSection.tsx
  src/app/inventory-page/DesktopStores.m.scss
  src/app/inventory-page/DesktopStores.m.scss.d.ts
  src/app/inventory-page/DesktopStores.tsx
  src/app/inventory-page/HeaderShadowDiv.m.scss
  src/app/inventory-page/HeaderShadowDiv.m.scss.d.ts
  src/app/inventory-page/HeaderShadowDiv.tsx
  src/app/inventory-page/Inventory.tsx
  src/app/inventory-page/InventoryCollapsibleTitle.scss
  src/app/inventory-page/InventoryCollapsibleTitle.tsx
  src/app/inventory-page/PhoneStores.tsx
  src/app/inventory-page/PhoneStoresHeader.m.scss
  src/app/inventory-page/PhoneStoresHeader.m.scss.d.ts
  src/app/inventory-page/PhoneStoresHeader.tsx
  src/app/inventory-page/StoreBucket.scss
  src/app/inventory-page/StoreBucket.tsx
  src/app/inventory-page/StoreBucketDropTarget.m.scss
  src/app/inventory-page/StoreBucketDropTarget.m.scss.d.ts
  src/app/inventory-page/StoreBucketDropTarget.tsx
  src/app/inventory-page/StoreBuckets.tsx
  src/app/inventory-page/StoreInventoryItem.tsx
  src/app/inventory-page/Stores.scss
  src/app/inventory-page/Stores.tsx
  src/app/item-popup/SocketDetails.tsx
  src/app/shell/Destiny.tsx
Labels: no changelog

#8270 Loadout tweaks
  src/app/destiny1/loadout-drawer/LoadoutDrawer.tsx
  src/app/destiny1/loadout-drawer/LoadoutDrawerOptions.m.scss
  src/app/destiny1/loadout-drawer/LoadoutDrawerOptions.tsx
  src/app/loadout-drawer/LoadoutDrawer2.tsx
  src/app/loadout-drawer/LoadoutDrawerContainer.tsx
Labels: no changelog

#8279 Don't use store-cell class for phone character carousel
  src/app/inventory-page/PhoneStoresHeader.m.scss
  src/app/inventory-page/PhoneStoresHeader.m.scss.d.ts
  src/app/inventory-page/PhoneStoresHeader.tsx
  src/app/inventory-page/Stores.scss
  src/app/inventory-page/Stores.tsx
Labels: no changelog

#8264 Avoid or justify accessing LoadoutItem.id
  src/app/destiny1/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/item-triage/ItemTriage.tsx
  src/app/loadout-builder/generated-sets/CompareDrawer.tsx
  src/app/loadout-builder/generated-sets/GeneratedSet.tsx
  src/app/loadout-drawer/LoadoutDrawer2.tsx
  src/app/loadout-drawer/loadout-apply.ts
  src/app/loadout-drawer/loadout-drawer-reducer.ts
  src/app/loadout-drawer/loadout-types.ts
  src/app/loadout-drawer/loadout-utils.ts
  src/app/organizer/Columns.tsx
  src/app/search/search-filters/loadouts.tsx
  src/app/search/search-filters/stats.tsx
Labels: no changelog

#8281 changelog check
  .github/workflows/changelog-check.yml
Labels: Changelog-None

#8284 add is:extraperk filter
  config/i18n.json
  src/app/search/__snapshots__/search-config.test.ts.snap
  src/app/search/search-filters/sockets.tsx
  src/locale/en.json
Labels: Changelog-Missing

#8282 Displayable perk determination fixes
  src/app/item-popup/PlugTooltip.tsx
  src/app/item-popup/SocketDetailsSelectedPlug.tsx
  src/app/loadout/plug-drawer/SelectablePlug.tsx
  src/app/utils/socket-utils.ts
Labels: Changelog-None

#8287 [Glaive] replacer
  src/app/dim-ui/rich-destiny-text.ts
Labels: Changelog-Missing

#8291 handle wishlists with perk recommendations and no stat parts
  src/app/armory/AllWishlistRolls.tsx
  src/app/armory/wishlist-collapser.ts
Labels: Changelog-Missing

#8297 Fix missing localization on insert button for super abilities
  config/i18n.json
  src/locale/en.json
Labels: Changelog-Missing

#8300 do base->enhanced fuzzy wishlist matching at time of matching
  src/app/item-popup/Plug.tsx
  src/app/wishlists/wishlist-file.test.ts
  src/app/wishlists/wishlist-file.ts
  src/app/wishlists/wishlists.ts
Labels: Changelog-Missing

#8305 lay out emote wheel with css
  src/app/item-popup/EmoteSockets.m.scss
  src/app/item-popup/EmoteSockets.tsx
Labels: Changelog-Missing

#8310 Fix lock armor element option
  src/app/loadout-builder/process/mappers.ts
  src/app/loadout/mod-utils.ts
Labels: Changelog-None

#8308 Fix pickPlugPositions rejecting possible assignment
  src/app/loadout/mod-assignment-utils.ts
Labels: Changelog-None

#8269 Types updates for react-redux beta
  .vscode/extensions.json
  .vscode/tasks.json
  src/app/accounts/MenuAccounts.tsx
  src/app/destiny1/loadout-builder/GeneratedSet.tsx
  src/app/inventory-page/StoreBucket.tsx
  src/app/inventory/ItemPopupTrigger.tsx
  src/app/item-actions/ActionButtons.tsx
  src/app/item-actions/ItemMoveLocations.tsx
  src/app/item-picker/ItemPicker.tsx
  src/app/item-popup/DesktopItemActions.tsx
  src/app/loadout-builder/generated-sets/GeneratedSetButtons.tsx
  src/app/loadout/loadout-menu/MaxlightButton.tsx
  src/app/shell/AccountRedirectRoute.tsx
  src/app/store/types.ts
Labels: Changelog-None, Changelog-Missing

#8318 Remove auto refresh for overfilled buckets
  docs/CHANGELOG.md
  src/app/inventory/item-move-service.ts
Labels: Changelog-Applied

#8319 Update Docker, set expectations
  Dockerfile
  docs/CONTRIBUTING.md
Labels: Changelog-Missing

#8320 Minor upgrades
  package.json
  src/app/dim-ui/ErrorBoundary.tsx
  src/app/dim-ui/Sheet.tsx
  src/app/loadout/plug-drawer/PlugDrawer.tsx
  src/app/shell/Header.tsx
  src/app/utils/hooks.ts
  yarn.lock
Labels: Changelog-None, Changelog-Missing

#8323 Another nameless item
  src/app/inventory/store/d2-item-factory.ts
Labels: Changelog-None, Changelog-Missing

#8322 Fix firefox event check
  src/app/utils/browsers.ts
Labels: Changelog-None

#8329 fix secondary collapser behavior and document a bit
  src/app/armory/wishlist-collapser.test.ts
  src/app/armory/wishlist-collapser.ts
Labels: Changelog-Missing

#8321 Move disabledDueToMaintenance to the loadout builder container
  src/app/loadout-builder/LoadoutBuilder.m.scss
  src/app/loadout-builder/LoadoutBuilder.m.scss.d.ts
  src/app/loadout-builder/LoadoutBuilder.tsx
  src/app/loadout-builder/LoadoutBuilderContainer.tsx
  src/app/loadout-builder/process/useProcess.ts
Labels: Changelog-None, Changelog-Missing

#8330 Various new lints and type fixes
  .eslintrc
  src/app/bungie-api/authenticated-fetch.ts
  src/app/bungie-api/rate-limit-config.ts
  src/app/bungie-api/rate-limiter.ts
  src/app/destiny1/activities/Activities.tsx
  src/app/destiny2/d2-definitions.ts
  src/app/dim-api/dim-api-helper.ts
  src/app/inventory/d2-stores.ts
  src/app/inventory/selectors.ts
  src/app/inventory/store/character-utils.ts
  src/app/search/query-parser.ts
  src/app/utils/hooks.ts
  src/app/vendors/actions.ts
  src/global.d.ts
Labels: Changelog-None, Changelog-Missing

#8335 Remove missing name workaround for 'The Flow, the Metal' emblem in French manifest
  src/app/inventory/store/d2-item-factory.ts
Labels: Changelog-None, Changelog-Missing

#8334 Fix missing highlighted objective flag on completed Deepsight weapons
  src/app/inventory/ItemIcon.tsx
Labels: Changelog-None, Changelog-Missing

#8339 Cleanup Triage and enable in Beta
  config/i18n.json
  config/webpack.js
  src/app/dim-ui/CollapsibleTitle.scss
  src/app/dim-ui/CollapsibleTitle.tsx
  src/app/dim-ui/SetFilterButton.m.scss
  src/app/dim-ui/SetFilterButton.tsx
  src/app/dim-ui/SpecialtyModSlotIcon.tsx
  src/app/item-popup/ItemPopupBody.scss
  src/app/item-popup/ItemPopupBody.tsx
  src/app/item-popup/ItemSockets.scss
  src/app/item-triage/ItemTriage.m.scss
  src/app/item-triage/ItemTriage.m.scss.d.ts
  src/app/item-triage/ItemTriage.tsx
  src/app/item-triage/TriageFactors.m.scss
  src/app/item-triage/TriageFactors.m.scss.d.ts
  src/app/item-triage/triage-factors.tsx
  src/app/item-triage/triage-utils.tsx
  src/app/search/search-filters/loadouts.tsx
  src/locale/en.json
Labels: Changelog-Missing

#8342 narrow similar counts by item tier and clearer loadout labels
  src/app/item-triage/ItemTriage.m.scss
  src/app/item-triage/ItemTriage.tsx
  src/app/item-triage/triage-factors.tsx
  src/app/item-triage/triage-utils.tsx
Labels: Changelog-Missing

#8336 Revert completed Deepsight weapon objective flag workaround
  src/app/inventory/ItemIcon.tsx
Labels: Changelog-None, Changelog-Missing

#8343 Replace some magic numbers with something more meaningful
  src/app/inventory/d2-stores.ts
  src/app/inventory/store-types.ts
  src/app/loadout-builder/filter/ExoticPicker.tsx
  src/app/store-stats/CharacterStats.tsx
Labels: Changelog-None

#8344 Always pick a backing store of the correct class in Loadout Drawer
  src/app/destiny1/loadout-drawer/LoadoutDrawer.tsx
  src/app/destiny1/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/item-triage/ItemTriage.tsx
  src/app/loadout-drawer/LoadoutDrawer2.tsx
  src/app/loadout-drawer/LoadoutDrawerContainer.tsx
  src/app/loadout-drawer/loadout-utils.ts
  src/app/loadout/loadout-ui/LoadoutItemCategorySection.tsx
  src/app/loadout/mod-assignment-drawer/ModAssignmentDrawer.tsx
  src/app/store-stats/CharacterStats.tsx
  src/app/store-stats/StoreStats.tsx
Labels: Changelog-None
