Repository DestinyItemManager/DIM, pull requests merged in 2022-03, with the labels that each got.

#7971 remove equipment buttons from emotes/finishers
  src/app/inventory/store/d2-item-factory.ts
  src/app/search/d2-known-values.ts
Labels: no changelog

#7970 don't show draggy hand when something can't be dragged
  src/app/inventory/DraggableInventoryItem.tsx
  src/app/inventory/InventoryItem.m.scss
Labels: no changelog

#8013 Yet another thing that needs rich destiny text
  src/app/item-popup/ItemPopupBody.tsx
Labels: no changelog

#8024 More efficient canDrag
  src/app/inventory/DraggableInventoryItem.tsx
Labels: no changelog

#8029 GHA: Lint & Test w/ Annotations
  .github/workflows/pr-build.yml
  .gitignore
  cspell.json
  package.json
Labels: Infrastructure: Build, no changelog

#7999 Add D1 types
  src/app/destiny1/activities/Activities.tsx
  src/app/destiny1/d1-buckets.ts
  src/app/destiny1/d1-definitions.ts
  src/app/destiny1/d1-manifest-types.ts
  src/app/destiny1/loadout-builder/D1LoadoutBuilder.tsx
  src/app/destiny1/record-books/RecordBooks.tsx
  src/app/destiny1/vendors/vendor.service.ts
  src/app/inventory/d1-stores.ts
  src/app/inventory/item-types.ts
  src/app/inventory/store-types.ts
  src/app/inventory/store/character-utils.ts
  src/app/inventory/store/d1-item-factory.ts
  src/app/inventory/store/d1-store-factory.ts
  src/app/inventory/store/objectives.ts
  src/app/loadout-drawer/loadout-item-conversion.ts
  src/app/organizer/ItemTypeSelector.tsx
  src/app/progress/LoadoutRequirementModifier.tsx
  src/app/progress/Objective.tsx
  src/app/progress/ObjectiveDescription.tsx
Labels: no changelog

#8032 bundlewatch.io test
  .github/workflows/deploy-beta.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/pr-build.yml
  package.json
  yarn.lock
Labels: no changelog

#8014 Reduce dependency on string bucket type
  src/app/destiny1/d1-bucket-categories.ts
  src/app/destiny1/d1-buckets.ts
  src/app/destiny1/loadout-builder/LoadoutBuilderLockPerk.tsx
  src/app/destiny2/d2-bucket-categories.ts
  src/app/destiny2/d2-buckets.ts
  src/app/inventory/inventory-buckets.ts
  src/app/inventory/selectors.ts
  src/app/inventory/spreadsheets.ts
  src/app/inventory/store/d1-item-factory.ts
  src/app/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/loadout-drawer/LoadoutDrawerDropTarget.tsx
  src/app/loadout-drawer/loadout-utils.ts
  src/app/loadout/LoadoutView.tsx
  src/app/loadout/loadout-edit/LoadoutEdit.tsx
  src/app/loadout/loadout-edit/LoadoutEditBucket.tsx
  src/app/loadout/loadout-ui/LoadoutItemCategorySection.tsx
  src/app/organizer/ItemTypeSelector.tsx
  src/app/progress/SolsticeOfHeroes.tsx
  src/app/progress/milestone-items.ts
  src/app/search/search-filters/known-values.tsx
  src/app/store-stats/VaultCapacity.tsx
Labels: no changelog

#8036 Fill in bucket for faked item from loadouts
  src/app/loadout-drawer/loadout-item-conversion.ts
Labels: no changelog

#8039 Don't include sidebar padding on phone
  src/app/inventory/Stores.scss
Labels: no changelog

#8040 Fix sheets dismissing with upward swipes
  src/app/dim-ui/Sheet.tsx
Labels: no changelog

#8038 Use PointerEvents for PressTip if available
  src/app/dim-ui/PressTip.tsx
Labels: no changelog

#8047 test and lint on cron to support forked PRs
  .github/workflows/pr-build.yml
  .github/workflows/test-and-lint-pr.yml
Labels: no changelog

#8049 GHA: yarn test and lint for forked PRs
  .github/workflows/deploy-beta.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/pr-build.yml
  .github/workflows/test-and-lint-pr.yml
Labels: no changelog

#8053 allow forked PRs to check bundlewatch status
  .github/workflows/deploy-beta.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/pr-build.yml
Labels: Infrastructure: Build, no changelog

#8054 Further distinguish pointer handling for PressTip
  src/app/dim-ui/PressTip.tsx
Labels: no changelog

#8055 Update bundlewatch
  .github/workflows/deploy-beta.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/pr-build.yml
  package.json
  yarn.lock
Labels: Infrastructure: Build, no changelog

#8058 Make sure the storage broken page can localize
  src/Index.tsx
Labels: no changelog

#8046 Strip out D2 concepts from old loadout drawer
  config/webpack.js
  src/app/loadout-drawer/GeneratedLoadoutStats.tsx
  src/app/loadout-drawer/LoadoutDrawer.tsx
  src/app/loadout-drawer/LoadoutDrawer2.tsx
  src/app/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/loadout-drawer/LoadoutDrawerOptions.tsx
  src/app/loadout-drawer/SavedModCategory.m.scss
  src/app/loadout-drawer/SavedModCategory.m.scss.d.ts
  src/app/loadout-drawer/SavedModCategory.tsx
  src/app/loadout-drawer/SavedMods.m.scss
  src/app/loadout-drawer/SavedMods.m.scss.d.ts
  src/app/loadout-drawer/SavedMods.tsx
  src/app/loadout-drawer/loadout-drawer-reducer.ts
  src/app/loadout-drawer/subclass-drawer/ItemSocketsSubclass.m.scss
  src/app/loadout-drawer/subclass-drawer/ItemSocketsSubclass.m.scss.d.ts
  src/app/loadout-drawer/subclass-drawer/ItemSocketsSubclass.tsx
  src/app/loadout-drawer/subclass-drawer/Subclass.m.scss
  src/app/loadout-drawer/subclass-drawer/Subclass.m.scss.d.ts
  src/app/loadout-drawer/subclass-drawer/Subclass.tsx
  src/app/loadout/loadout-edit/LoadoutEdit.tsx
  src/app/shell/Destiny.tsx
  src/global.d.ts
Labels: no changelog

#8062 Add aliases for docs, locale, and testing
  config/webpack.js
  jest.config.js
  src/app/destiny2/d2-definitions.test.ts
  src/app/i18n.ts
  src/app/inventory/d2-stores.test.ts
  src/app/item-popup/item-popup-actions.test.ts
  src/app/loadout-builder/process-utils.test.ts
  src/app/loadout-builder/process/mappers.test.ts
  src/app/whats-new/ChangeLog.tsx
  tsconfig.json
Labels: no changelog

#8060 Remove shift key handling from loadouts
  src/app/item-actions/ActionButtons.tsx
  src/app/loadout-drawer/LoadoutDrawer.tsx
  src/app/loadout-drawer/LoadoutDrawer2.tsx
  src/app/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/loadout-drawer/LoadoutDrawerDropTarget.tsx
  src/app/loadout-drawer/loadout-drawer-reducer.ts
  src/app/loadout-drawer/loadout-events.ts
  src/app/loadout/loadout-edit/LoadoutEdit.tsx
Labels: no changelog

#8043 Deepsight and shaped weapon item tile improvements
  src/app/_variables.scss
  src/app/inventory/BadgeInfo.m.scss
  src/app/inventory/BadgeInfo.m.scss.d.ts
  src/app/inventory/BadgeInfo.tsx
  src/app/inventory/ItemIcon.m.scss
  src/app/inventory/ItemIcon.m.scss.d.ts
  src/app/inventory/ItemIcon.tsx
  src/app/item-popup/ItemPopupBody.scss
  src/images/deepsight.png
  src/images/shaped.png
Labels: no changelog

#8066 Darken background behind code on the change log
  src/app/whats-new/ChangeLog.scss
Labels: no changelog

#8063 Rename loadout item "equipped" to "equip" in order to separate it from DimItem
  src/app/infuse/InfusionFinder.tsx
  src/app/loadout-builder/generated-sets/CompareDrawer.tsx
  src/app/loadout-builder/generated-sets/GeneratedSet.tsx
  src/app/loadout-builder/loadout-builder-reducer.ts
  src/app/loadout-drawer/LoadoutDrawerBucket.tsx
  src/app/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/loadout-drawer/LoadoutPopup.tsx
  src/app/loadout-drawer/loadout-apply.ts
  src/app/loadout-drawer/loadout-drawer-reducer.ts
  src/app/loadout-drawer/loadout-item-conversion.ts
  src/app/loadout-drawer/loadout-type-converters.ts
  src/app/loadout-drawer/loadout-types.ts
  src/app/loadout-drawer/loadout-utils.ts
  src/app/loadout/LoadoutView.tsx
  src/app/loadout/fashion/FashionDrawer.tsx
  src/app/loadout/loadout-edit/LoadoutEdit.tsx
  src/app/loadout/mod-assignment-drawer/selectors.ts
Labels: no changelog

#8067 Hide Masterwork socket on shaped weapons and Memento socket on non-shaped weapons
  src/app/inventory/store/crafted.ts
  src/app/item-popup/ItemSocketsWeapons.tsx
Labels: no changelog

#8065 Weapon level filter
  config/i18n.json
  src/app/dim-ui/ItemCategoryIcon.m.scss
  src/app/search/search-filters/range-numeric.tsx
  src/locale/dim.json
Labels: no changelog

#8072 Fix jest search filters snapshot
  src/app/search/__snapshots__/search-config.test.ts.snap
Labels: no changelog

#8059 Bundlewatch bye bye, Hello Relative-CI
  .github/workflows/deploy-beta.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/pr-build.yml
  .github/workflows/relative-ci.yml
  .gitignore
  config/webpack.js
  package.json
  yarn.lock
Labels: no changelog

#8074 Discord Bot Test
  .github/workflows/discord-bot-test.yml
Labels: no changelog

#8076 discord embeds
  .github/workflows/i18n-bot-upload.yml
Labels: Infrastructure: i18n, no changelog

#8070 Fix LO mods picker requiring two confirmations
  src/app/loadout/ModPicker.tsx
  src/app/loadout/plug-drawer/PlugDrawer.tsx
Labels: no changelog

#8077 Only reload when DIM is in the background
  src/app/dim-ui/ActivityTracker.tsx
Labels: no changelog

#8079 exclude unneeded assets
  config/webpack.js
Labels: no changelog

#8075 Locale reorganization
  .github/workflows/i18n-bot-download.yml
  .github/workflows/i18n-bot-upload-all.yml
  .github/workflows/i18n-bot-upload.yml
  .github/workflows/i18n-update.yml
  config/webpack.js
  cspell.json
  docs/CONTRIBUTING.md
  i18next-scanner.config.js
  src/app/i18n.ts
  src/build-browsercheck-utils.js
  src/global.d.ts
  src/locale/de.json
  src/locale/en.json
  src/locale/es.json
  src/locale/esMX.json
  src/locale/fr.json
  src/locale/it.json
  src/locale/ja.json
  src/locale/ko.json
  src/locale/pl.json
  src/locale/ptBR.json
  src/locale/ru.json
  src/locale/zhCHS.json
  src/locale/zhCHT.json
Labels: no changelog

#8078 Move old loadout drawer into destiny1 folder
  src/app/destiny1/loadout-drawer/Buttons.m.scss
  src/app/destiny1/loadout-drawer/Buttons.m.scss.d.ts
  src/app/destiny1/loadout-drawer/Buttons.tsx
  src/app/destiny1/loadout-drawer/LoadoutDrawer.tsx
  src/app/destiny1/loadout-drawer/LoadoutDrawerBucket.m.scss
  src/app/destiny1/loadout-drawer/LoadoutDrawerBucket.m.scss.d.ts
  src/app/destiny1/loadout-drawer/LoadoutDrawerBucket.tsx
  src/app/destiny1/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/destiny1/loadout-drawer/LoadoutDrawerItem.tsx
  src/app/destiny1/loadout-drawer/LoadoutDrawerOptions.m.scss
  src/app/destiny1/loadout-drawer/LoadoutDrawerOptions.m.scss.d.ts
  src/app/destiny1/loadout-drawer/LoadoutDrawerOptions.tsx
  src/app/destiny1/loadout-drawer/loadout-drawer.scss
  src/app/shell/Destiny.tsx
Labels: no changelog

#7864 GHA: Versioning
  .github/workflows/deploy-beta.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/pr-build.yml
  build/deploy-prod.sh
  build/sentry-release-prod.sh
  build/sentry-release.sh
  config/webpack.js
Labels: Infrastructure: Build, no changelog

#7879 GHA: Sentry
  .github/workflows/deploy-beta.yml
  .github/workflows/deploy-prod.yml
  .sentryclirc
  build/sentry-release.sh
  package.json
  yarn.lock
Labels: Infrastructure: Build, no changelog

#8086 Relative CI upkeep
  .github/workflows/deploy-beta.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/relative-ci.yml
Labels: Infrastructure: Build, no changelog

#8091 show PL for classified armor/weapons
  src/app/inventory/store/d2-item-factory.ts
Labels: no changelog

#8096 gradient fix for enhanced perks
  src/app/item-popup/Plug.tsx
Labels: no changelog

#8109 Move perk icons in front of enhanced trait gradient
  src/app/item-popup/Plug.tsx
Labels: no changelog

#8107 Fix for crafting socket being displayed in the armory
  src/app/item-popup/ItemSocketsWeapons.tsx
Labels: no changelog

#8082 Disable autofocus on iOS
  src/app/item-popup/NotesArea.tsx
  src/app/loadout/plug-drawer/PlugDrawer.tsx
Labels: no changelog

#8117 only send stats to relative-ci on relative-ci labeled PRs
  .github/workflows/relative-ci.yml
Labels: no changelog, relative-ci

#8120 only changelog check on non-draft / lint and test on workflow run via artifacts
  .github/workflows/changelog-check.yml
  .github/workflows/jest-and-lint-annotate.yml
  .github/workflows/pr-build.yml
  package.json
Labels: no changelog

#8123 GHA: Artifacts
  .github/workflows/jest-and-lint-annotate.yml
  .github/workflows/pr-build.yml
Labels: no changelog

#8124 PR should fail for both test and lint
  .github/workflows/changelog-check.yml
  .github/workflows/jest-and-lint-annotate.yml
  .github/workflows/pr-build.yml
  .github/workflows/pr-test-and-lint.yml
Labels: no changelog

#8127 GHA: Test - Jest and Lint
  .github/workflows/changelog-check.yml
  .github/workflows/jest-and-lint-annotate.yml
  .github/workflows/pr-test-and-lint.yml
Labels: Infrastructure: Build

#8092 FontAwesome Subset
  config/webpack.js
  package.json
  src/data/webfonts/fa-brands-400.eot
  src/data/webfonts/fa-brands-400.svg
  src/data/webfonts/fa-brands-400.ttf
  src/data/webfonts/fa-brands-400.woff
  src/data/webfonts/fa-brands-400.woff2
  src/data/webfonts/fa-regular-400.eot
  src/data/webfonts/fa-regular-400.svg
  src/data/webfonts/fa-regular-400.ttf
  src/data/webfonts/fa-regular-400.woff
  src/data/webfonts/fa-regular-400.woff2
  src/data/webfonts/fa-solid-900.eot
  src/data/webfonts/fa-solid-900.svg
  src/data/webfonts/fa-solid-900.ttf
  src/data/webfonts/fa-solid-900.woff
  src/data/webfonts/fa-solid-900.woff2
  src/fa-subset.mjs
  yarn.lock
Labels: Infrastructure: Build, no changelog

#8083 Replace DimLoadoutItem with ResolvedLoadoutItem
  src/app/destiny1/loadout-drawer/LoadoutDrawer.tsx
  src/app/destiny1/loadout-drawer/LoadoutDrawerBucket.tsx
  src/app/destiny1/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/loadout-builder/filter/LockArmorAndPerks.tsx
  src/app/loadout-builder/generated-sets/CompareDrawer.tsx
  src/app/loadout-builder/generated-sets/GeneratedSet.tsx
  src/app/loadout-builder/generated-sets/GeneratedSetButtons.tsx
  src/app/loadout-builder/generated-sets/GeneratedSets.tsx
  src/app/loadout-builder/loadout-builder-reducer.ts
  src/app/loadout-builder/process/useProcess.ts
  src/app/loadout-drawer/LoadoutDrawer2.tsx
  src/app/loadout-drawer/loadout-drawer-reducer.ts
  src/app/loadout-drawer/loadout-item-conversion.ts
  src/app/loadout-drawer/loadout-types.ts
  src/app/loadout-drawer/loadout-utils.ts
  src/app/loadout/LoadoutView.tsx
  src/app/loadout/fashion/FashionDrawer.tsx
  src/app/loadout/loadout-edit/LoadoutEdit.tsx
  src/app/loadout/loadout-edit/LoadoutEditBucket.tsx
  src/app/loadout/loadout-edit/LoadoutEditSubclass.tsx
  src/app/loadout/loadout-ui/LoadoutItemCategorySection.tsx
  src/app/loadout/loadout-ui/LoadoutSubclassSection.tsx
  src/app/loadout/mod-assignment-drawer/ModAssignmentDrawer.tsx
  src/app/loadout/mod-assignment-drawer/selectors.ts
Labels: no changelog

#8140 Tell sentry when we skip cleaning infos
  src/app/inventory/dim-item-info.ts
Labels: no changelog

#8142 D1 fixes
  src/app/destiny1/d1-buckets.ts
  src/app/destiny1/vendors/D1Vendors.tsx
  src/app/destiny2/d2-buckets.ts
Labels: no changelog

#8089 rsync via GHA
  .github/workflows/deploy-beta.yml
Labels: Infrastructure: Build, no changelog

#8145 The forbidden bucket strikes again (it's mods this time)
  src/app/inventory/store/d2-item-factory.ts
Labels: no changelog

#8141 Move loadout drawer under a container component
  src/app/destiny1/loadout-drawer/LoadoutDrawer.tsx
  src/app/destiny1/loadout-drawer/LoadoutDrawerBucket.tsx
  src/app/destiny1/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/destiny1/loadout-drawer/LoadoutDrawerItem.tsx
  src/app/loadout-drawer/LoadoutDrawer2.tsx
  src/app/loadout-drawer/LoadoutDrawerContainer.tsx
  src/app/loadout-drawer/loadout-drawer-reducer.ts
  src/app/loadout-drawer/loadout-item-conversion.ts
  src/app/loadout-drawer/loadout-utils.ts
  src/app/loadout/loadout-edit/LoadoutEdit.tsx
  src/app/loadout/loadout-edit/LoadoutEditBucket.tsx
  src/app/loadout/loadout-edit/LoadoutEditBucketDropTarget.tsx
  src/app/shell/Destiny.tsx
Labels: no changelog

#8158 Fix mod assignment drawer
  src/app/loadout/mod-assignment-drawer/ModAssignmentDrawer.tsx
  src/app/loadout/mod-assignment-drawer/selectors.ts
Labels: no changelog

#8154 Wrong character power level warning
  config/i18n.json
  src/app/destiny1/loadout-drawer/LoadoutDrawer.tsx
  src/app/destiny1/loadout-drawer/loadout-drawer.scss
  src/app/dim-ui/AlertIcon.m.scss
  src/app/dim-ui/AlertIcon.m.scss.d.ts
  src/app/dim-ui/AlertIcon.tsx
  src/app/dim-ui/SetFilterButton.m.scss
  src/app/dim-ui/SetFilterButton.m.scss.d.ts
  src/app/dim-ui/SetFilterButton.tsx
  src/app/gear-power/GearPower.m.scss
  src/app/gear-power/GearPower.m.scss.d.ts
  src/app/gear-power/GearPower.tsx
  src/app/inventory/ItemPowerSet.m.scss
  src/app/inventory/MoveNotifications.m.scss
  src/app/inventory/MoveNotifications.tsx
  src/app/inventory/d2-stores.ts
  src/app/inventory/store-types.ts
  src/app/loadout-drawer/LoadoutPopup.m.scss
  src/app/loadout-drawer/LoadoutPopup.tsx
  src/app/loadout/LoadoutView.tsx
  src/app/store-stats/CharacterStats.scss
  src/app/store-stats/CharacterStats.tsx
  src/locale/en.json
Labels: no changelog

#8164 no-op: relocate contents of shell/filters. redo tier name handling
  src/app/character-tile/CharacterHeaderXP.tsx
  src/app/compare/Compare.tsx
  src/app/compare/CompareStat.tsx
  src/app/destiny1/loadout-builder/D1LoadoutBuilder.tsx
  src/app/dim-ui/WeaponCraftedInfo.tsx
  src/app/inventory/ArtifactXP.tsx
  src/app/inventory/BadgeInfo.tsx
  src/app/inventory/InventoryItem.tsx
  src/app/inventory/StoreBucket.tsx
  src/app/inventory/item-move-service.ts
  src/app/inventory/item-types.ts
  src/app/inventory/store/d2-item-factory.ts
  src/app/item-feed/ItemFeed.tsx
  src/app/item-picker/ItemPicker.tsx
  src/app/item-popup/ItemPopup.tsx
  src/app/item-popup/ItemPopupBody.tsx
  src/app/item-popup/ItemPopupHeader.tsx
  src/app/item-popup/ItemStat.tsx
  src/app/loadout-drawer/auto-loadouts.ts
  src/app/loadout-drawer/postmaster.ts
  src/app/organizer/Columns.tsx
  src/app/progress/Objective.tsx
  src/app/progress/Pursuit.tsx
  src/app/progress/PursuitItem.tsx
  src/app/records/PlugSet.tsx
  src/app/records/PresentationNode.tsx
  src/app/records/Record.tsx
  src/app/search/SearchResults.tsx
  src/app/search/d2-known-values.ts
  src/app/search/search-filters/known-values.tsx
  src/app/shell/formatters.ts
  src/app/shell/item-comparators.ts
  src/app/storage/LocalStorageInfo.tsx
  src/app/store-stats/D1CharacterStats.tsx
Labels: no changelog

#8172 add reversible item sorting
  config/i18n.json
  src/app/inventory/StoreBucket.tsx
  src/app/item-picker/ItemPicker.tsx
  src/app/search/SearchResults.tsx
  src/app/settings/SettingsPage.tsx
  src/app/settings/SortOrderEditor.scss
  src/app/settings/SortOrderEditor.tsx
  src/app/settings/initial-settings.ts
  src/app/settings/item-sort.ts
  src/app/shell/item-comparators.ts
  src/locale/en.json
Labels: no changelog

#8189 Compress even if compressing makes files bigger
  config/webpack.js
Labels: no changelog

#8194 relative-ci label fix
  .github/workflows/pr-build.yml
  .github/workflows/relative-ci.yml
Labels: no changelog

#8193 Start a test for wishlist parsing
  src/app/wishlists/wishlist-file.test.ts
Labels: no changelog

#8162 Clean up plug picker.
  src/app/loadout/ModPicker.tsx
  src/app/loadout/SubclassPlugDrawer.tsx
  src/app/loadout/plug-drawer/Footer.tsx
  src/app/loadout/plug-drawer/PlugDrawer.tsx
  src/app/loadout/plug-drawer/PlugSection.tsx
  src/app/loadout/plug-drawer/types.ts
Labels: no changelog

#8215 cspell updates
  .github/workflows/check-spelling.yml
  config/cspell/bungie-dict.txt
  config/cspell/dim-dict.txt
  config/cspell/dim-username-dict.txt
  config/cspell/programming-dict.txt
  cspell-dim-dict.txt
  cspell.json
  src/app/loadout-drawer/loadout-drawer-reducer.ts
Labels: no changelog

#8209 Move loadout search to the top of the loadout popup
  src/app/loadout-drawer/LoadoutPopup.tsx
Labels: no changelog

#8207 Fix loadouts drawer not opening on "create loadout" via Vault
  src/app/loadout-drawer/LoadoutDrawer2.tsx
Labels: no changelog

#8205 Support comments in searches
  src/app/search/__snapshots__/query-parser.test.ts.snap
  src/app/search/query-parser.test.ts
  src/app/search/query-parser.ts
Labels: Feature: Search, no changelog

#8210 Chill out on updates
  src/app/dim-api/actions.ts
  src/app/dim-ui/ActivityTracker.tsx
Labels: no changelog

#8203 Search validate length
  src/app/dim-api/reducer.ts
  src/app/search/MainSearchBarActions.tsx
  src/app/search/SearchBar.tsx
  src/app/search/search-utils.ts
Labels: Feature: Search, no changelog

#8192 Remove pointer events from item children
  src/app/inventory/InventoryItem.m.scss
Labels: no changelog

#8185 Clean up LoadoutDrawer reducer
  src/app/destiny1/loadout-drawer/LoadoutDrawer.tsx
  src/app/destiny1/loadout-drawer/LoadoutDrawerContents.tsx
  src/app/destiny1/loadout-drawer/LoadoutDrawerOptions.tsx
  src/app/loadout-drawer/LoadoutDrawer2.tsx
  src/app/loadout-drawer/loadout-drawer-reducer.ts
  src/app/loadout-drawer/loadout-utils.ts
  src/app/loadout/loadout-edit/LoadoutEdit.tsx
Labels: no changelog

#8190 Enable the React automatic runtime
  .eslintrc
  babel.config.js
Labels: no changelog

#8187 Upgrades
  package.json
  src/app/loadout-drawer/LoadoutPopup.tsx
  src/app/loadout/Loadouts.tsx
  src/app/settings/SettingsPage.tsx
  src/app/settings/initial-settings.ts
  src/app/shell/Header.tsx
  yarn.lock
Labels: no changelog

#7642 Switch AnimatedValue to Framer Motion
  src/app/dim-ui/AnimatedNumber.tsx
Labels: no changelog

#8224 only update relative-ci on PRs that change the build pipeline
  .github/workflows/pr-build.yml
Labels: Infrastructure: Build

#8231 make a materials count sheet
  config/i18n.json
  src/app/inventory/Inventory.tsx
  src/app/loadout-drawer/LoadoutPopup.m.scss
  src/app/loadout-drawer/LoadoutPopup.tsx
  src/app/material-counts/MaterialCounts.m.scss
  src/app/material-counts/MaterialCounts.m.scss.d.ts
  src/app/material-counts/MaterialCounts.tsx
  src/app/material-counts/MaterialCountsWrappers.tsx
  src/app/store-stats/CharacterStats.tsx
  src/app/store-stats/MaterialCounts.tsx
  src/app/store-stats/VaultCapacity.tsx
  src/locale/en.json
Labels: no changelog

#8228 show crafting requirements.. sort of
  src/app/inventory/item-types.ts
  src/app/inventory/store/sockets.ts
  src/app/item-popup/Plug.tsx
  src/app/item-popup/PlugTooltip.tsx
  src/app/item-popup/Socket.tsx
  yarn.lock
Labels: no changelog

#8236 Upgrades
  yarn.lock
Labels: no changelog

#8234 Fix some loadout drawer category buttons doing the wrong thing
  src/app/loadout-drawer/loadout-drawer-reducer.ts
  src/app/loadout/loadout-edit/LoadoutEdit.tsx
Labels: no changelog

#8233 Add an option to disable SnoreToast notifications
  config/webpack.js
Labels: no changelog

#8211 Loadout share UI
  config/i18n.json
  src/app/loadout/Loadouts.tsx
  src/app/loadout/loadout-share/LoadoutShareSheet.m.scss
  src/app/loadout/loadout-share/LoadoutShareSheet.m.scss.d.ts
  src/app/loadout/loadout-share/LoadoutShareSheet.tsx
  src/app/shell/icons/Library.ts
  src/locale/en.json
Labels: no changelog

#8201 Manual scroll compare
  config/i18n.json
  docs/CHANGELOG.md
  src/app/compare/Compare.m.scss
  src/app/compare/Compare.m.scss.d.ts
  src/app/compare/Compare.tsx
  src/app/compare/CompareItem.m.scss
  src/app/compare/CompareStat.tsx
  src/app/dim-ui/Sheet.tsx
  src/app/utils/browsers.ts
  src/locale/en.json
Labels: Feature: Item Comparison

#8237 Select on focus in the loadout share UI
  src/app/loadout/loadout-share/LoadoutShareSheet.tsx
Labels: no changelog

#8232 override plurals; add i18n language object
  src/app/i18n.ts
  src/app/search/search-filters/freeform.tsx
  src/build-browsercheck-utils.js
Labels: i18n, no changelog

#8239 Don't run svgo-loader in dev
  config/webpack.js
Labels: no changelog

#8242 Actually await manifest json
  src/app/manifest/manifest-service-json.ts
Labels: no changelog

#8241 Don't fill in singular items from unequipped
  config/i18n.json
  src/app/loadout-drawer/loadout-drawer-reducer.ts
  src/app/loadout-drawer/loadout-utils.ts
  src/locale/en.json
Labels: no changelog

#8238 Set accent-color
  src/app/main.scss
Labels: no changelog

#8246 Fix loadout apply getting confused about item IDs
  src/app/loadout-drawer/loadout-apply.ts
Labels: no changelog

#8251 Fix missing version from dev-server
  config/webpack.js
Labels: no changelog

#8254 disable enhanced elemental capacitor
  src/app/search/d2-known-values.ts
  src/app/utils/item-utils.ts
Labels: no changelog

#8257 allow other hostnames in dev
  config/webpack.js
Labels: no changelog

#8259 Wishlist collapse
  src/app/armory/AllWishlistRolls.m.scss
  src/app/armory/AllWishlistRolls.m.scss.d.ts
  src/app/armory/AllWishlistRolls.tsx
  src/app/armory/wishlistCollapser.test.ts
  src/app/armory/wishlistCollapser.ts
Labels: no changelog
